# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from ...requests.pagination import PaginationParams
from .list_namespaces_response_namespaces_item import ListNamespacesResponseNamespacesItemParams


class ListNamespacesResponseParams(typing_extensions.TypedDict):
    namespaces: typing.Sequence[ListNamespacesResponseNamespacesItemParams]
    """
    Namespaces on this page, newest first
    """

    pagination: PaginationParams
    """
    Pagination metadata
    """
