# This file was auto-generated by Fern from our API Definition.

import typing

import httpx

from supermemory._types import NOT_GIVEN, NotGiven

from .. import core
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..requests.document_input import DocumentInputParams
from ..requests.metadata_value import MetadataValueParams
from ..types.batch_add_result import BatchAddResult
from ..types.delete_documents_result import DeleteDocumentsResult
from ..types.document import Document
from ..types.document_ref import DocumentRef
from .raw_client import AsyncRawDocumentsClient, RawDocumentsClient
from .types.batch_add_documents_request_dreaming import BatchAddDocumentsRequestDreaming
from .types.batch_add_documents_request_task_type import BatchAddDocumentsRequestTaskType
from .types.get_documents_request_include_item import GetDocumentsRequestIncludeItem
from .types.replace_with_file_documents_request_dreaming import ReplaceWithFileDocumentsRequestDreaming
from .types.replace_with_file_documents_request_file_type import ReplaceWithFileDocumentsRequestFileType
from .types.replace_with_file_documents_request_task_type import ReplaceWithFileDocumentsRequestTaskType
from .types.update_documents_request_dreaming import UpdateDocumentsRequestDreaming
from .types.update_documents_request_task_type import UpdateDocumentsRequestTaskType
from .types.update_file_documents_request_dreaming import UpdateFileDocumentsRequestDreaming
from .types.update_file_documents_request_file_type import UpdateFileDocumentsRequestFileType
from .types.update_file_documents_request_task_type import UpdateFileDocumentsRequestTaskType
from .types.upload_file_documents_request_dreaming import UploadFileDocumentsRequestDreaming
from .types.upload_file_documents_request_file_type import UploadFileDocumentsRequestFileType
from .types.upload_file_documents_request_task_type import UploadFileDocumentsRequestTaskType

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class DocumentsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawDocumentsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawDocumentsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawDocumentsClient
        """
        return self._raw_client

    def delete(
        self,
        namespace: str,
        *,
        ids: typing.Sequence[str],
        request_options: typing.Optional[RequestOptions] = None,
        extra_headers: typing.Optional[typing.Mapping[str, str]] = None,
        extra_query: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        extra_body: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        timeout: typing.Union[float, httpx.Timeout, None, NotGiven] = NOT_GIVEN,
    ) -> DeleteDocumentsResult:
        """
        Permanently remove documents and their derived knowledge by document ID or caller-defined ID. Each requested ID is handled independently so successful deletions are preserved when another ID fails.

        Parameters
        ----------
        namespace : str
            The isolated namespace. This can be an ID for your user, a project ID, or any other identifier you wish to use to scope documents.

        ids : typing.Sequence[str]
            Document identifiers to permanently delete from this namespace

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeleteDocumentsResult
            Document deletion completed

        Examples
        --------
        from supermemory import Supermemory

        client = Supermemory(
            api_key="YOUR_API_KEY",
        )
        client.documents.delete(
            namespace="user_alex",
            ids=["my-doc-123"],
        )
        """
        _response = self._raw_client.delete(namespace, ids=ids, request_options=request_options)
        return _response.data

    def batch_add(
        self,
        namespace: str,
        *,
        documents: typing.Sequence[DocumentInputParams],
        task_type: typing.Optional[BatchAddDocumentsRequestTaskType] = OMIT,
        dreaming: typing.Optional[BatchAddDocumentsRequestDreaming] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
        extra_headers: typing.Optional[typing.Mapping[str, str]] = None,
        extra_query: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        extra_body: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        timeout: typing.Union[float, httpx.Timeout, None, NotGiven] = NOT_GIVEN,
    ) -> BatchAddResult:
        """
        Build a knowledge base efficiently by ingesting up to 600 text or URL documents at once. Existing caller-defined IDs append new information using the same semantics as single-document ingestion.

        Parameters
        ----------
        namespace : str
            The isolated namespace. This can be an ID for your user, a project ID, or any other identifier you wish to use to scope documents.

        documents : typing.Sequence[DocumentInputParams]
            Documents to ingest or append in one request

        task_type : typing.Optional[BatchAddDocumentsRequestTaskType]
            Processing pipeline. "memory" builds durable learned context; "superrag" optimizes the document for retrieval without generating memories.

        dreaming : typing.Optional[BatchAddDocumentsRequestDreaming]
            Processing mode. "dynamic" (default) groups related documents so memories form from coherent context. "instant" processes each document independently right away and bills one extra operation per document.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BatchAddResult
            Batch accepted for processing

        Examples
        --------
        from supermemory import Supermemory

        client = Supermemory(
            api_key="YOUR_API_KEY",
        )
        client.documents.batch_add(
            namespace="user_alex",
            documents=[
                {
                    "content": "Supermemory turns unstructured content into evolving memory."
                }
            ],
        )
        """
        _response = self._raw_client.batch_add(
            namespace, documents=documents, task_type=task_type, dreaming=dreaming, request_options=request_options
        )
        return _response.data

    def get(
        self,
        namespace: str,
        id: str,
        *,
        include: typing.Optional[
            typing.Union[GetDocumentsRequestIncludeItem, typing.Sequence[GetDocumentsRequestIncludeItem]]
        ] = None,
        request_options: typing.Optional[RequestOptions] = None,
        extra_headers: typing.Optional[typing.Mapping[str, str]] = None,
        extra_query: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        extra_body: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        timeout: typing.Union[float, httpx.Timeout, None, NotGiven] = NOT_GIVEN,
    ) -> Document:
        """
        Retrieve a document's canonical content, metadata, and processing state by document ID or caller-defined ID. Optionally include its source chunks, derived memories, or both in the same response.

        Parameters
        ----------
        namespace : str
            The isolated namespace. This can be an ID for your user, a project ID, or any other identifier you wish to use to scope documents.

        id : str
            The public document ID

        include : typing.Optional[typing.Union[GetDocumentsRequestIncludeItem, typing.Sequence[GetDocumentsRequestIncludeItem]]]
            Comma-separated child resources to include: chunks, memories, or both.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Document
            Document retrieved successfully

        Examples
        --------
        from supermemory import Supermemory

        client = Supermemory(
            api_key="YOUR_API_KEY",
        )
        client.documents.get(
            namespace="user_alex",
            id="my-doc-123",
        )
        """
        _response = self._raw_client.get(namespace, id, include=include, request_options=request_options)
        return _response.data

    def update(
        self,
        namespace: str,
        id: str,
        *,
        content: typing.Optional[str] = OMIT,
        supporting_context: typing.Optional[str] = OMIT,
        metadata: typing.Optional[typing.Dict[str, MetadataValueParams]] = OMIT,
        group: typing.Optional[typing.Dict[str, MetadataValueParams]] = OMIT,
        date: typing.Optional[str] = OMIT,
        task_type: typing.Optional[UpdateDocumentsRequestTaskType] = OMIT,
        dreaming: typing.Optional[UpdateDocumentsRequestDreaming] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
        extra_headers: typing.Optional[typing.Mapping[str, str]] = None,
        extra_query: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        extra_body: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        timeout: typing.Union[float, httpx.Timeout, None, NotGiven] = NOT_GIVEN,
    ) -> DocumentRef:
        """
        Refresh an existing document without changing its stable ID. Supplied content replaces the canonical content and is reprocessed; omitted fields remain unchanged.

        Parameters
        ----------
        namespace : str
            The isolated namespace. This can be an ID for your user, a project ID, or any other identifier you wish to use to scope documents.

        id : str
            The public document ID

        content : typing.Optional[str]
            The content to process. This may be plaintext or a URL to supported rich content.

        supporting_context : typing.Optional[str]
            Context used to guide memory extraction within this namespace. Max 1500 characters.

        metadata : typing.Optional[typing.Dict[str, MetadataValueParams]]
            Arbitrary metadata attached to the document and derived data

        group : typing.Optional[typing.Dict[str, MetadataValueParams]]
            Metadata values that isolate related context within the namespace

        date : typing.Optional[str]
            When the source content is from, in ISO 8601 format

        task_type : typing.Optional[UpdateDocumentsRequestTaskType]
            Processing pipeline. "memory" builds durable learned context; "superrag" optimizes the document for retrieval without generating memories.

        dreaming : typing.Optional[UpdateDocumentsRequestDreaming]
            Processing mode. "dynamic" (default) groups related documents so memories form from coherent context. "instant" processes each document independently right away and bills one extra operation per document.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DocumentRef
            Document updated successfully

        Examples
        --------
        from supermemory import Supermemory

        client = Supermemory(
            api_key="YOUR_API_KEY",
        )
        client.documents.update(
            namespace="user_alex",
            id="my-doc-123",
        )
        """
        _response = self._raw_client.update(
            namespace,
            id,
            content=content,
            supporting_context=supporting_context,
            metadata=metadata,
            group=group,
            date=date,
            task_type=task_type,
            dreaming=dreaming,
            request_options=request_options,
        )
        return _response.data

    def upload_file(
        self,
        namespace: str,
        *,
        file: core.File,
        supporting_context: typing.Optional[str] = OMIT,
        metadata: typing.Optional[str] = OMIT,
        group: typing.Optional[str] = OMIT,
        date: typing.Optional[str] = OMIT,
        task_type: typing.Optional[UploadFileDocumentsRequestTaskType] = OMIT,
        dreaming: typing.Optional[UploadFileDocumentsRequestDreaming] = OMIT,
        file_type: typing.Optional[UploadFileDocumentsRequestFileType] = OMIT,
        mime_type: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
        extra_headers: typing.Optional[typing.Mapping[str, str]] = None,
        extra_query: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        extra_body: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        timeout: typing.Union[float, httpx.Timeout, None, NotGiven] = NOT_GIVEN,
    ) -> DocumentRef:
        """
        Transform an uploaded file into searchable knowledge and learned memory. The response returns as soon as ingestion is safely queued while extraction and memory formation continue asynchronously.

        Parameters
        ----------
        namespace : str
            The isolated namespace. This can be an ID for your user, a project ID, or any other identifier you wish to use to scope documents.

        file : core.File
            See core.File for more documentation

        supporting_context : typing.Optional[str]
            Context used to guide memory extraction within this namespace. Max 1500 characters.

        metadata : typing.Optional[str]
            JSON-encoded metadata to attach to the document and its derived memories

        group : typing.Optional[str]
            JSON-encoded metadata used to keep related context isolated during processing and recall

        date : typing.Optional[str]
            When the source content is from, in ISO 8601 format

        task_type : typing.Optional[UploadFileDocumentsRequestTaskType]
            Processing pipeline. "memory" builds durable learned context; "superrag" optimizes the document for retrieval without generating memories.

        dreaming : typing.Optional[UploadFileDocumentsRequestDreaming]
            Processing mode. "dynamic" (default) groups related documents so memories form from coherent context. "instant" processes each document independently right away and bills one extra operation per document.

        file_type : typing.Optional[UploadFileDocumentsRequestFileType]
            Explicit source type used when automatic inference is insufficient

        mime_type : typing.Optional[str]
            Explicit MIME type used when upload metadata is insufficient

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DocumentRef
            File accepted for processing

        Examples
        --------
        from supermemory import Supermemory

        client = Supermemory(
            api_key="YOUR_API_KEY",
        )
        client.documents.upload_file(
            namespace="user_alex",
        )
        """
        _response = self._raw_client.upload_file(
            namespace,
            file=file,
            supporting_context=supporting_context,
            metadata=metadata,
            group=group,
            date=date,
            task_type=task_type,
            dreaming=dreaming,
            file_type=file_type,
            mime_type=mime_type,
            request_options=request_options,
        )
        return _response.data

    def replace_with_file(
        self,
        namespace: str,
        id: str,
        *,
        file: core.File,
        supporting_context: typing.Optional[str] = OMIT,
        metadata: typing.Optional[str] = OMIT,
        group: typing.Optional[str] = OMIT,
        date: typing.Optional[str] = OMIT,
        task_type: typing.Optional[ReplaceWithFileDocumentsRequestTaskType] = OMIT,
        dreaming: typing.Optional[ReplaceWithFileDocumentsRequestDreaming] = OMIT,
        file_type: typing.Optional[ReplaceWithFileDocumentsRequestFileType] = OMIT,
        mime_type: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
        extra_headers: typing.Optional[typing.Mapping[str, str]] = None,
        extra_query: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        extra_body: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        timeout: typing.Union[float, httpx.Timeout, None, NotGiven] = NOT_GIVEN,
    ) -> DocumentRef:
        """
        Replace an existing document with a new file while keeping its stable document ID. Content and caller metadata are overwritten, then the document is reprocessed asynchronously.

        Parameters
        ----------
        namespace : str
            The isolated namespace. This can be an ID for your user, a project ID, or any other identifier you wish to use to scope documents.

        id : str
            The public document ID

        file : core.File
            See core.File for more documentation

        supporting_context : typing.Optional[str]
            Context used to guide memory extraction within this namespace. Max 1500 characters.

        metadata : typing.Optional[str]
            JSON-encoded metadata to attach to the document and its derived memories

        group : typing.Optional[str]
            JSON-encoded metadata used to keep related context isolated during processing and recall

        date : typing.Optional[str]
            When the source content is from, in ISO 8601 format

        task_type : typing.Optional[ReplaceWithFileDocumentsRequestTaskType]
            Processing pipeline. "memory" builds durable learned context; "superrag" optimizes the document for retrieval without generating memories.

        dreaming : typing.Optional[ReplaceWithFileDocumentsRequestDreaming]
            Processing mode. "dynamic" (default) groups related documents so memories form from coherent context. "instant" processes each document independently right away and bills one extra operation per document.

        file_type : typing.Optional[ReplaceWithFileDocumentsRequestFileType]
            Explicit source type used when automatic inference is insufficient

        mime_type : typing.Optional[str]
            Explicit MIME type used when upload metadata is insufficient

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DocumentRef
            Replacement accepted for processing

        Examples
        --------
        from supermemory import Supermemory

        client = Supermemory(
            api_key="YOUR_API_KEY",
        )
        client.documents.replace_with_file(
            namespace="user_alex",
            id="my-doc-123",
        )
        """
        _response = self._raw_client.replace_with_file(
            namespace,
            id,
            file=file,
            supporting_context=supporting_context,
            metadata=metadata,
            group=group,
            date=date,
            task_type=task_type,
            dreaming=dreaming,
            file_type=file_type,
            mime_type=mime_type,
            request_options=request_options,
        )
        return _response.data

    def update_file(
        self,
        namespace: str,
        id: str,
        *,
        file: typing.Optional[core.File] = OMIT,
        supporting_context: typing.Optional[str] = OMIT,
        metadata: typing.Optional[str] = OMIT,
        group: typing.Optional[str] = OMIT,
        date: typing.Optional[str] = OMIT,
        task_type: typing.Optional[UpdateFileDocumentsRequestTaskType] = OMIT,
        dreaming: typing.Optional[UpdateFileDocumentsRequestDreaming] = OMIT,
        file_type: typing.Optional[UpdateFileDocumentsRequestFileType] = OMIT,
        mime_type: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
        extra_headers: typing.Optional[typing.Mapping[str, str]] = None,
        extra_query: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        extra_body: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        timeout: typing.Union[float, httpx.Timeout, None, NotGiven] = NOT_GIVEN,
    ) -> DocumentRef:
        """
        Refresh only the file-backed fields you provide. Supplying a file replaces the canonical content; omitted metadata and processing context remain unchanged.

        Parameters
        ----------
        namespace : str
            The isolated namespace. This can be an ID for your user, a project ID, or any other identifier you wish to use to scope documents.

        id : str
            The public document ID

        file : typing.Optional[core.File]
            See core.File for more documentation

        supporting_context : typing.Optional[str]
            Context used to guide memory extraction within this namespace. Max 1500 characters.

        metadata : typing.Optional[str]
            JSON-encoded metadata to attach to the document and its derived memories

        group : typing.Optional[str]
            JSON-encoded metadata used to keep related context isolated during processing and recall

        date : typing.Optional[str]
            When the source content is from, in ISO 8601 format

        task_type : typing.Optional[UpdateFileDocumentsRequestTaskType]
            Processing pipeline. "memory" builds durable learned context; "superrag" optimizes the document for retrieval without generating memories.

        dreaming : typing.Optional[UpdateFileDocumentsRequestDreaming]
            Processing mode. "dynamic" (default) groups related documents so memories form from coherent context. "instant" processes each document independently right away and bills one extra operation per document.

        file_type : typing.Optional[UpdateFileDocumentsRequestFileType]
            Explicit source type used when automatic inference is insufficient

        mime_type : typing.Optional[str]
            Explicit MIME type used when upload metadata is insufficient

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DocumentRef
            Update accepted for processing

        Examples
        --------
        from supermemory import Supermemory

        client = Supermemory(
            api_key="YOUR_API_KEY",
        )
        client.documents.update_file(
            namespace="user_alex",
            id="my-doc-123",
        )
        """
        _response = self._raw_client.update_file(
            namespace,
            id,
            file=file,
            supporting_context=supporting_context,
            metadata=metadata,
            group=group,
            date=date,
            task_type=task_type,
            dreaming=dreaming,
            file_type=file_type,
            mime_type=mime_type,
            request_options=request_options,
        )
        return _response.data


class AsyncDocumentsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawDocumentsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawDocumentsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawDocumentsClient
        """
        return self._raw_client

    async def delete(
        self,
        namespace: str,
        *,
        ids: typing.Sequence[str],
        request_options: typing.Optional[RequestOptions] = None,
        extra_headers: typing.Optional[typing.Mapping[str, str]] = None,
        extra_query: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        extra_body: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        timeout: typing.Union[float, httpx.Timeout, None, NotGiven] = NOT_GIVEN,
    ) -> DeleteDocumentsResult:
        """
        Permanently remove documents and their derived knowledge by document ID or caller-defined ID. Each requested ID is handled independently so successful deletions are preserved when another ID fails.

        Parameters
        ----------
        namespace : str
            The isolated namespace. This can be an ID for your user, a project ID, or any other identifier you wish to use to scope documents.

        ids : typing.Sequence[str]
            Document identifiers to permanently delete from this namespace

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeleteDocumentsResult
            Document deletion completed

        Examples
        --------
        import asyncio

        from supermemory import AsyncSupermemory

        client = AsyncSupermemory(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.documents.delete(
                namespace="user_alex",
                ids=["my-doc-123"],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(namespace, ids=ids, request_options=request_options)
        return _response.data

    async def batch_add(
        self,
        namespace: str,
        *,
        documents: typing.Sequence[DocumentInputParams],
        task_type: typing.Optional[BatchAddDocumentsRequestTaskType] = OMIT,
        dreaming: typing.Optional[BatchAddDocumentsRequestDreaming] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
        extra_headers: typing.Optional[typing.Mapping[str, str]] = None,
        extra_query: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        extra_body: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        timeout: typing.Union[float, httpx.Timeout, None, NotGiven] = NOT_GIVEN,
    ) -> BatchAddResult:
        """
        Build a knowledge base efficiently by ingesting up to 600 text or URL documents at once. Existing caller-defined IDs append new information using the same semantics as single-document ingestion.

        Parameters
        ----------
        namespace : str
            The isolated namespace. This can be an ID for your user, a project ID, or any other identifier you wish to use to scope documents.

        documents : typing.Sequence[DocumentInputParams]
            Documents to ingest or append in one request

        task_type : typing.Optional[BatchAddDocumentsRequestTaskType]
            Processing pipeline. "memory" builds durable learned context; "superrag" optimizes the document for retrieval without generating memories.

        dreaming : typing.Optional[BatchAddDocumentsRequestDreaming]
            Processing mode. "dynamic" (default) groups related documents so memories form from coherent context. "instant" processes each document independently right away and bills one extra operation per document.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BatchAddResult
            Batch accepted for processing

        Examples
        --------
        import asyncio

        from supermemory import AsyncSupermemory

        client = AsyncSupermemory(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.documents.batch_add(
                namespace="user_alex",
                documents=[
                    {
                        "content": "Supermemory turns unstructured content into evolving memory."
                    }
                ],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.batch_add(
            namespace, documents=documents, task_type=task_type, dreaming=dreaming, request_options=request_options
        )
        return _response.data

    async def get(
        self,
        namespace: str,
        id: str,
        *,
        include: typing.Optional[
            typing.Union[GetDocumentsRequestIncludeItem, typing.Sequence[GetDocumentsRequestIncludeItem]]
        ] = None,
        request_options: typing.Optional[RequestOptions] = None,
        extra_headers: typing.Optional[typing.Mapping[str, str]] = None,
        extra_query: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        extra_body: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        timeout: typing.Union[float, httpx.Timeout, None, NotGiven] = NOT_GIVEN,
    ) -> Document:
        """
        Retrieve a document's canonical content, metadata, and processing state by document ID or caller-defined ID. Optionally include its source chunks, derived memories, or both in the same response.

        Parameters
        ----------
        namespace : str
            The isolated namespace. This can be an ID for your user, a project ID, or any other identifier you wish to use to scope documents.

        id : str
            The public document ID

        include : typing.Optional[typing.Union[GetDocumentsRequestIncludeItem, typing.Sequence[GetDocumentsRequestIncludeItem]]]
            Comma-separated child resources to include: chunks, memories, or both.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Document
            Document retrieved successfully

        Examples
        --------
        import asyncio

        from supermemory import AsyncSupermemory

        client = AsyncSupermemory(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.documents.get(
                namespace="user_alex",
                id="my-doc-123",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(namespace, id, include=include, request_options=request_options)
        return _response.data

    async def update(
        self,
        namespace: str,
        id: str,
        *,
        content: typing.Optional[str] = OMIT,
        supporting_context: typing.Optional[str] = OMIT,
        metadata: typing.Optional[typing.Dict[str, MetadataValueParams]] = OMIT,
        group: typing.Optional[typing.Dict[str, MetadataValueParams]] = OMIT,
        date: typing.Optional[str] = OMIT,
        task_type: typing.Optional[UpdateDocumentsRequestTaskType] = OMIT,
        dreaming: typing.Optional[UpdateDocumentsRequestDreaming] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
        extra_headers: typing.Optional[typing.Mapping[str, str]] = None,
        extra_query: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        extra_body: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        timeout: typing.Union[float, httpx.Timeout, None, NotGiven] = NOT_GIVEN,
    ) -> DocumentRef:
        """
        Refresh an existing document without changing its stable ID. Supplied content replaces the canonical content and is reprocessed; omitted fields remain unchanged.

        Parameters
        ----------
        namespace : str
            The isolated namespace. This can be an ID for your user, a project ID, or any other identifier you wish to use to scope documents.

        id : str
            The public document ID

        content : typing.Optional[str]
            The content to process. This may be plaintext or a URL to supported rich content.

        supporting_context : typing.Optional[str]
            Context used to guide memory extraction within this namespace. Max 1500 characters.

        metadata : typing.Optional[typing.Dict[str, MetadataValueParams]]
            Arbitrary metadata attached to the document and derived data

        group : typing.Optional[typing.Dict[str, MetadataValueParams]]
            Metadata values that isolate related context within the namespace

        date : typing.Optional[str]
            When the source content is from, in ISO 8601 format

        task_type : typing.Optional[UpdateDocumentsRequestTaskType]
            Processing pipeline. "memory" builds durable learned context; "superrag" optimizes the document for retrieval without generating memories.

        dreaming : typing.Optional[UpdateDocumentsRequestDreaming]
            Processing mode. "dynamic" (default) groups related documents so memories form from coherent context. "instant" processes each document independently right away and bills one extra operation per document.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DocumentRef
            Document updated successfully

        Examples
        --------
        import asyncio

        from supermemory import AsyncSupermemory

        client = AsyncSupermemory(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.documents.update(
                namespace="user_alex",
                id="my-doc-123",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(
            namespace,
            id,
            content=content,
            supporting_context=supporting_context,
            metadata=metadata,
            group=group,
            date=date,
            task_type=task_type,
            dreaming=dreaming,
            request_options=request_options,
        )
        return _response.data

    async def upload_file(
        self,
        namespace: str,
        *,
        file: core.File,
        supporting_context: typing.Optional[str] = OMIT,
        metadata: typing.Optional[str] = OMIT,
        group: typing.Optional[str] = OMIT,
        date: typing.Optional[str] = OMIT,
        task_type: typing.Optional[UploadFileDocumentsRequestTaskType] = OMIT,
        dreaming: typing.Optional[UploadFileDocumentsRequestDreaming] = OMIT,
        file_type: typing.Optional[UploadFileDocumentsRequestFileType] = OMIT,
        mime_type: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
        extra_headers: typing.Optional[typing.Mapping[str, str]] = None,
        extra_query: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        extra_body: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        timeout: typing.Union[float, httpx.Timeout, None, NotGiven] = NOT_GIVEN,
    ) -> DocumentRef:
        """
        Transform an uploaded file into searchable knowledge and learned memory. The response returns as soon as ingestion is safely queued while extraction and memory formation continue asynchronously.

        Parameters
        ----------
        namespace : str
            The isolated namespace. This can be an ID for your user, a project ID, or any other identifier you wish to use to scope documents.

        file : core.File
            See core.File for more documentation

        supporting_context : typing.Optional[str]
            Context used to guide memory extraction within this namespace. Max 1500 characters.

        metadata : typing.Optional[str]
            JSON-encoded metadata to attach to the document and its derived memories

        group : typing.Optional[str]
            JSON-encoded metadata used to keep related context isolated during processing and recall

        date : typing.Optional[str]
            When the source content is from, in ISO 8601 format

        task_type : typing.Optional[UploadFileDocumentsRequestTaskType]
            Processing pipeline. "memory" builds durable learned context; "superrag" optimizes the document for retrieval without generating memories.

        dreaming : typing.Optional[UploadFileDocumentsRequestDreaming]
            Processing mode. "dynamic" (default) groups related documents so memories form from coherent context. "instant" processes each document independently right away and bills one extra operation per document.

        file_type : typing.Optional[UploadFileDocumentsRequestFileType]
            Explicit source type used when automatic inference is insufficient

        mime_type : typing.Optional[str]
            Explicit MIME type used when upload metadata is insufficient

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DocumentRef
            File accepted for processing

        Examples
        --------
        import asyncio

        from supermemory import AsyncSupermemory

        client = AsyncSupermemory(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.documents.upload_file(
                namespace="user_alex",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.upload_file(
            namespace,
            file=file,
            supporting_context=supporting_context,
            metadata=metadata,
            group=group,
            date=date,
            task_type=task_type,
            dreaming=dreaming,
            file_type=file_type,
            mime_type=mime_type,
            request_options=request_options,
        )
        return _response.data

    async def replace_with_file(
        self,
        namespace: str,
        id: str,
        *,
        file: core.File,
        supporting_context: typing.Optional[str] = OMIT,
        metadata: typing.Optional[str] = OMIT,
        group: typing.Optional[str] = OMIT,
        date: typing.Optional[str] = OMIT,
        task_type: typing.Optional[ReplaceWithFileDocumentsRequestTaskType] = OMIT,
        dreaming: typing.Optional[ReplaceWithFileDocumentsRequestDreaming] = OMIT,
        file_type: typing.Optional[ReplaceWithFileDocumentsRequestFileType] = OMIT,
        mime_type: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
        extra_headers: typing.Optional[typing.Mapping[str, str]] = None,
        extra_query: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        extra_body: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        timeout: typing.Union[float, httpx.Timeout, None, NotGiven] = NOT_GIVEN,
    ) -> DocumentRef:
        """
        Replace an existing document with a new file while keeping its stable document ID. Content and caller metadata are overwritten, then the document is reprocessed asynchronously.

        Parameters
        ----------
        namespace : str
            The isolated namespace. This can be an ID for your user, a project ID, or any other identifier you wish to use to scope documents.

        id : str
            The public document ID

        file : core.File
            See core.File for more documentation

        supporting_context : typing.Optional[str]
            Context used to guide memory extraction within this namespace. Max 1500 characters.

        metadata : typing.Optional[str]
            JSON-encoded metadata to attach to the document and its derived memories

        group : typing.Optional[str]
            JSON-encoded metadata used to keep related context isolated during processing and recall

        date : typing.Optional[str]
            When the source content is from, in ISO 8601 format

        task_type : typing.Optional[ReplaceWithFileDocumentsRequestTaskType]
            Processing pipeline. "memory" builds durable learned context; "superrag" optimizes the document for retrieval without generating memories.

        dreaming : typing.Optional[ReplaceWithFileDocumentsRequestDreaming]
            Processing mode. "dynamic" (default) groups related documents so memories form from coherent context. "instant" processes each document independently right away and bills one extra operation per document.

        file_type : typing.Optional[ReplaceWithFileDocumentsRequestFileType]
            Explicit source type used when automatic inference is insufficient

        mime_type : typing.Optional[str]
            Explicit MIME type used when upload metadata is insufficient

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DocumentRef
            Replacement accepted for processing

        Examples
        --------
        import asyncio

        from supermemory import AsyncSupermemory

        client = AsyncSupermemory(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.documents.replace_with_file(
                namespace="user_alex",
                id="my-doc-123",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.replace_with_file(
            namespace,
            id,
            file=file,
            supporting_context=supporting_context,
            metadata=metadata,
            group=group,
            date=date,
            task_type=task_type,
            dreaming=dreaming,
            file_type=file_type,
            mime_type=mime_type,
            request_options=request_options,
        )
        return _response.data

    async def update_file(
        self,
        namespace: str,
        id: str,
        *,
        file: typing.Optional[core.File] = OMIT,
        supporting_context: typing.Optional[str] = OMIT,
        metadata: typing.Optional[str] = OMIT,
        group: typing.Optional[str] = OMIT,
        date: typing.Optional[str] = OMIT,
        task_type: typing.Optional[UpdateFileDocumentsRequestTaskType] = OMIT,
        dreaming: typing.Optional[UpdateFileDocumentsRequestDreaming] = OMIT,
        file_type: typing.Optional[UpdateFileDocumentsRequestFileType] = OMIT,
        mime_type: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
        extra_headers: typing.Optional[typing.Mapping[str, str]] = None,
        extra_query: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        extra_body: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        timeout: typing.Union[float, httpx.Timeout, None, NotGiven] = NOT_GIVEN,
    ) -> DocumentRef:
        """
        Refresh only the file-backed fields you provide. Supplying a file replaces the canonical content; omitted metadata and processing context remain unchanged.

        Parameters
        ----------
        namespace : str
            The isolated namespace. This can be an ID for your user, a project ID, or any other identifier you wish to use to scope documents.

        id : str
            The public document ID

        file : typing.Optional[core.File]
            See core.File for more documentation

        supporting_context : typing.Optional[str]
            Context used to guide memory extraction within this namespace. Max 1500 characters.

        metadata : typing.Optional[str]
            JSON-encoded metadata to attach to the document and its derived memories

        group : typing.Optional[str]
            JSON-encoded metadata used to keep related context isolated during processing and recall

        date : typing.Optional[str]
            When the source content is from, in ISO 8601 format

        task_type : typing.Optional[UpdateFileDocumentsRequestTaskType]
            Processing pipeline. "memory" builds durable learned context; "superrag" optimizes the document for retrieval without generating memories.

        dreaming : typing.Optional[UpdateFileDocumentsRequestDreaming]
            Processing mode. "dynamic" (default) groups related documents so memories form from coherent context. "instant" processes each document independently right away and bills one extra operation per document.

        file_type : typing.Optional[UpdateFileDocumentsRequestFileType]
            Explicit source type used when automatic inference is insufficient

        mime_type : typing.Optional[str]
            Explicit MIME type used when upload metadata is insufficient

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DocumentRef
            Update accepted for processing

        Examples
        --------
        import asyncio

        from supermemory import AsyncSupermemory

        client = AsyncSupermemory(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.documents.update_file(
                namespace="user_alex",
                id="my-doc-123",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_file(
            namespace,
            id,
            file=file,
            supporting_context=supporting_context,
            metadata=metadata,
            group=group,
            date=date,
            task_type=task_type,
            dreaming=dreaming,
            file_type=file_type,
            mime_type=mime_type,
            request_options=request_options,
        )
        return _response.data
