# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .get_memories_request_include_item import GetMemoriesRequestIncludeItem
    from .get_memories_response import GetMemoriesResponse
    from .get_memories_response_included import GetMemoriesResponseIncluded
    from .get_memories_response_included_document import GetMemoriesResponseIncludedDocument
    from .get_memories_response_included_document_system import GetMemoriesResponseIncludedDocumentSystem
    from .get_memories_response_included_related import GetMemoriesResponseIncludedRelated
    from .get_memories_response_included_related_children_item import GetMemoriesResponseIncludedRelatedChildrenItem
    from .get_memories_response_included_related_children_item_document import (
        GetMemoriesResponseIncludedRelatedChildrenItemDocument,
    )
    from .get_memories_response_included_related_children_item_document_system import (
        GetMemoriesResponseIncludedRelatedChildrenItemDocumentSystem,
    )
    from .get_memories_response_included_related_children_item_system import (
        GetMemoriesResponseIncludedRelatedChildrenItemSystem,
    )
    from .get_memories_response_included_related_parents_item import GetMemoriesResponseIncludedRelatedParentsItem
    from .get_memories_response_included_related_parents_item_document import (
        GetMemoriesResponseIncludedRelatedParentsItemDocument,
    )
    from .get_memories_response_included_related_parents_item_document_system import (
        GetMemoriesResponseIncludedRelatedParentsItemDocumentSystem,
    )
    from .get_memories_response_included_related_parents_item_system import (
        GetMemoriesResponseIncludedRelatedParentsItemSystem,
    )
    from .get_memories_response_included_related_siblings_item import GetMemoriesResponseIncludedRelatedSiblingsItem
    from .get_memories_response_included_related_siblings_item_document import (
        GetMemoriesResponseIncludedRelatedSiblingsItemDocument,
    )
    from .get_memories_response_included_related_siblings_item_document_system import (
        GetMemoriesResponseIncludedRelatedSiblingsItemDocumentSystem,
    )
    from .get_memories_response_included_related_siblings_item_system import (
        GetMemoriesResponseIncludedRelatedSiblingsItemSystem,
    )
_dynamic_imports: typing.Dict[str, str] = {
    "GetMemoriesRequestIncludeItem": ".get_memories_request_include_item",
    "GetMemoriesResponse": ".get_memories_response",
    "GetMemoriesResponseIncluded": ".get_memories_response_included",
    "GetMemoriesResponseIncludedDocument": ".get_memories_response_included_document",
    "GetMemoriesResponseIncludedDocumentSystem": ".get_memories_response_included_document_system",
    "GetMemoriesResponseIncludedRelated": ".get_memories_response_included_related",
    "GetMemoriesResponseIncludedRelatedChildrenItem": ".get_memories_response_included_related_children_item",
    "GetMemoriesResponseIncludedRelatedChildrenItemDocument": ".get_memories_response_included_related_children_item_document",
    "GetMemoriesResponseIncludedRelatedChildrenItemDocumentSystem": ".get_memories_response_included_related_children_item_document_system",
    "GetMemoriesResponseIncludedRelatedChildrenItemSystem": ".get_memories_response_included_related_children_item_system",
    "GetMemoriesResponseIncludedRelatedParentsItem": ".get_memories_response_included_related_parents_item",
    "GetMemoriesResponseIncludedRelatedParentsItemDocument": ".get_memories_response_included_related_parents_item_document",
    "GetMemoriesResponseIncludedRelatedParentsItemDocumentSystem": ".get_memories_response_included_related_parents_item_document_system",
    "GetMemoriesResponseIncludedRelatedParentsItemSystem": ".get_memories_response_included_related_parents_item_system",
    "GetMemoriesResponseIncludedRelatedSiblingsItem": ".get_memories_response_included_related_siblings_item",
    "GetMemoriesResponseIncludedRelatedSiblingsItemDocument": ".get_memories_response_included_related_siblings_item_document",
    "GetMemoriesResponseIncludedRelatedSiblingsItemDocumentSystem": ".get_memories_response_included_related_siblings_item_document_system",
    "GetMemoriesResponseIncludedRelatedSiblingsItemSystem": ".get_memories_response_included_related_siblings_item_system",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "GetMemoriesRequestIncludeItem",
    "GetMemoriesResponse",
    "GetMemoriesResponseIncluded",
    "GetMemoriesResponseIncludedDocument",
    "GetMemoriesResponseIncludedDocumentSystem",
    "GetMemoriesResponseIncludedRelated",
    "GetMemoriesResponseIncludedRelatedChildrenItem",
    "GetMemoriesResponseIncludedRelatedChildrenItemDocument",
    "GetMemoriesResponseIncludedRelatedChildrenItemDocumentSystem",
    "GetMemoriesResponseIncludedRelatedChildrenItemSystem",
    "GetMemoriesResponseIncludedRelatedParentsItem",
    "GetMemoriesResponseIncludedRelatedParentsItemDocument",
    "GetMemoriesResponseIncludedRelatedParentsItemDocumentSystem",
    "GetMemoriesResponseIncludedRelatedParentsItemSystem",
    "GetMemoriesResponseIncludedRelatedSiblingsItem",
    "GetMemoriesResponseIncludedRelatedSiblingsItemDocument",
    "GetMemoriesResponseIncludedRelatedSiblingsItemDocumentSystem",
    "GetMemoriesResponseIncludedRelatedSiblingsItemSystem",
]
