# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel
from .get_memories_response_included_related_children_item import GetMemoriesResponseIncludedRelatedChildrenItem
from .get_memories_response_included_related_parents_item import GetMemoriesResponseIncludedRelatedParentsItem
from .get_memories_response_included_related_siblings_item import GetMemoriesResponseIncludedRelatedSiblingsItem


class GetMemoriesResponseIncludedRelated(UncheckedBaseModel):
    """
    Present when include has related
    """

    parents: typing.List[GetMemoriesResponseIncludedRelatedParentsItem] = pydantic.Field()
    """
    Earlier versions this memory updates, nearest first
    """

    children: typing.List[GetMemoriesResponseIncludedRelatedChildrenItem] = pydantic.Field()
    """
    Newer versions that update this memory, nearest first
    """

    siblings: typing.List[GetMemoriesResponseIncludedRelatedSiblingsItem] = pydantic.Field()
    """
    Memories connected by extends or derives, nearest first
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
