# This file was auto-generated by Fern from our API Definition.

import typing

import httpx

from supermemory._types import NOT_GIVEN, NotGiven

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawFeedbackClient, RawFeedbackClient
from .types.post_feedback_request_type import PostFeedbackRequestType
from .types.post_feedback_response import PostFeedbackResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class FeedbackClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawFeedbackClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawFeedbackClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawFeedbackClient
        """
        return self._raw_client

    def post_feedback(
        self,
        *,
        type: PostFeedbackRequestType,
        title: str,
        description: str,
        endpoint: typing.Optional[str] = OMIT,
        request_id: typing.Optional[str] = OMIT,
        expected: typing.Optional[str] = OMIT,
        actual: typing.Optional[str] = OMIT,
        client: typing.Optional[str] = OMIT,
        contact_email: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
        extra_headers: typing.Optional[typing.Mapping[str, str]] = None,
        extra_query: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        extra_body: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        timeout: typing.Union[float, httpx.Timeout, None, NotGiven] = NOT_GIVEN,
    ) -> PostFeedbackResponse:
        """
        Report a bug, request a feature or flag a docs problem to the Supermemory team. Built for AI agents: send structured JSON and an engineer picks it up.

        Authentication is optional for requests with a usable client IP. Cross-zone Cloudflare Worker requests and requests without a client IP must provide an API key. With an API key the limit is 3 submissions per organization per UTC day; without one it is 3 per IPv4 address or IPv6 /64, shared with everyone behind that address. Authenticated submissions have a separate 200/day pool; anonymous submissions share a 20/day pool. Pass your API key to get your own quota.

        Parameters
        ----------
        type : PostFeedbackRequestType
            Kind of feedback

        title : str
            One-line summary

        description : str
            What happened, with enough detail for an engineer to act on it

        endpoint : typing.Optional[str]
            API operation the feedback is about

        request_id : typing.Optional[str]
            Request ID of a failing call, if there is one

        expected : typing.Optional[str]
            What you expected to happen

        actual : typing.Optional[str]
            What actually happened

        client : typing.Optional[str]
            Agent, tool or SDK sending the feedback

        contact_email : typing.Optional[str]
            Where to reach you about this feedback

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostFeedbackResponse
            Feedback received

        Examples
        --------
        from supermemory import Supermemory

        client = Supermemory(
            api_key="YOUR_API_KEY",
        )
        client.feedback.post_feedback(
            type="bug",
            title="Search returns no results for documents still in indexing",
            description="Documents added less than a minute ago are missing from /v4/search results even though GET /v3/documents/{id} reports status done.",
        )
        """
        _response = self._raw_client.post_feedback(
            type=type,
            title=title,
            description=description,
            endpoint=endpoint,
            request_id=request_id,
            expected=expected,
            actual=actual,
            client=client,
            contact_email=contact_email,
            request_options=request_options,
        )
        return _response.data


class AsyncFeedbackClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawFeedbackClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawFeedbackClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawFeedbackClient
        """
        return self._raw_client

    async def post_feedback(
        self,
        *,
        type: PostFeedbackRequestType,
        title: str,
        description: str,
        endpoint: typing.Optional[str] = OMIT,
        request_id: typing.Optional[str] = OMIT,
        expected: typing.Optional[str] = OMIT,
        actual: typing.Optional[str] = OMIT,
        client: typing.Optional[str] = OMIT,
        contact_email: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
        extra_headers: typing.Optional[typing.Mapping[str, str]] = None,
        extra_query: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        extra_body: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        timeout: typing.Union[float, httpx.Timeout, None, NotGiven] = NOT_GIVEN,
    ) -> PostFeedbackResponse:
        """
        Report a bug, request a feature or flag a docs problem to the Supermemory team. Built for AI agents: send structured JSON and an engineer picks it up.

        Authentication is optional for requests with a usable client IP. Cross-zone Cloudflare Worker requests and requests without a client IP must provide an API key. With an API key the limit is 3 submissions per organization per UTC day; without one it is 3 per IPv4 address or IPv6 /64, shared with everyone behind that address. Authenticated submissions have a separate 200/day pool; anonymous submissions share a 20/day pool. Pass your API key to get your own quota.

        Parameters
        ----------
        type : PostFeedbackRequestType
            Kind of feedback

        title : str
            One-line summary

        description : str
            What happened, with enough detail for an engineer to act on it

        endpoint : typing.Optional[str]
            API operation the feedback is about

        request_id : typing.Optional[str]
            Request ID of a failing call, if there is one

        expected : typing.Optional[str]
            What you expected to happen

        actual : typing.Optional[str]
            What actually happened

        client : typing.Optional[str]
            Agent, tool or SDK sending the feedback

        contact_email : typing.Optional[str]
            Where to reach you about this feedback

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostFeedbackResponse
            Feedback received

        Examples
        --------
        import asyncio

        from supermemory import AsyncSupermemory

        client = AsyncSupermemory(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.feedback.post_feedback(
                type="bug",
                title="Search returns no results for documents still in indexing",
                description="Documents added less than a minute ago are missing from /v4/search results even though GET /v3/documents/{id} reports status done.",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.post_feedback(
            type=type,
            title=title,
            description=description,
            endpoint=endpoint,
            request_id=request_id,
            expected=expected,
            actual=actual,
            client=client,
            contact_email=contact_email,
            request_options=request_options,
        )
        return _response.data
