# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .batch_add_documents_request_dreaming import BatchAddDocumentsRequestDreaming
    from .batch_add_documents_request_task_type import BatchAddDocumentsRequestTaskType
    from .get_documents_request_include_item import GetDocumentsRequestIncludeItem
    from .replace_with_file_documents_request_dreaming import ReplaceWithFileDocumentsRequestDreaming
    from .replace_with_file_documents_request_file_type import ReplaceWithFileDocumentsRequestFileType
    from .replace_with_file_documents_request_task_type import ReplaceWithFileDocumentsRequestTaskType
    from .update_documents_request_dreaming import UpdateDocumentsRequestDreaming
    from .update_documents_request_task_type import UpdateDocumentsRequestTaskType
    from .update_file_documents_request_dreaming import UpdateFileDocumentsRequestDreaming
    from .update_file_documents_request_file_type import UpdateFileDocumentsRequestFileType
    from .update_file_documents_request_task_type import UpdateFileDocumentsRequestTaskType
    from .upload_file_documents_request_dreaming import UploadFileDocumentsRequestDreaming
    from .upload_file_documents_request_file_type import UploadFileDocumentsRequestFileType
    from .upload_file_documents_request_task_type import UploadFileDocumentsRequestTaskType
_dynamic_imports: typing.Dict[str, str] = {
    "BatchAddDocumentsRequestDreaming": ".batch_add_documents_request_dreaming",
    "BatchAddDocumentsRequestTaskType": ".batch_add_documents_request_task_type",
    "GetDocumentsRequestIncludeItem": ".get_documents_request_include_item",
    "ReplaceWithFileDocumentsRequestDreaming": ".replace_with_file_documents_request_dreaming",
    "ReplaceWithFileDocumentsRequestFileType": ".replace_with_file_documents_request_file_type",
    "ReplaceWithFileDocumentsRequestTaskType": ".replace_with_file_documents_request_task_type",
    "UpdateDocumentsRequestDreaming": ".update_documents_request_dreaming",
    "UpdateDocumentsRequestTaskType": ".update_documents_request_task_type",
    "UpdateFileDocumentsRequestDreaming": ".update_file_documents_request_dreaming",
    "UpdateFileDocumentsRequestFileType": ".update_file_documents_request_file_type",
    "UpdateFileDocumentsRequestTaskType": ".update_file_documents_request_task_type",
    "UploadFileDocumentsRequestDreaming": ".upload_file_documents_request_dreaming",
    "UploadFileDocumentsRequestFileType": ".upload_file_documents_request_file_type",
    "UploadFileDocumentsRequestTaskType": ".upload_file_documents_request_task_type",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "BatchAddDocumentsRequestDreaming",
    "BatchAddDocumentsRequestTaskType",
    "GetDocumentsRequestIncludeItem",
    "ReplaceWithFileDocumentsRequestDreaming",
    "ReplaceWithFileDocumentsRequestFileType",
    "ReplaceWithFileDocumentsRequestTaskType",
    "UpdateDocumentsRequestDreaming",
    "UpdateDocumentsRequestTaskType",
    "UpdateFileDocumentsRequestDreaming",
    "UpdateFileDocumentsRequestFileType",
    "UpdateFileDocumentsRequestTaskType",
    "UploadFileDocumentsRequestDreaming",
    "UploadFileDocumentsRequestFileType",
    "UploadFileDocumentsRequestTaskType",
]
