# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .get_memories_response import GetMemoriesResponseParams
    from .get_memories_response_included import GetMemoriesResponseIncludedParams
    from .get_memories_response_included_document import GetMemoriesResponseIncludedDocumentParams
    from .get_memories_response_included_document_system import GetMemoriesResponseIncludedDocumentSystemParams
    from .get_memories_response_included_related import GetMemoriesResponseIncludedRelatedParams
    from .get_memories_response_included_related_children_item import (
        GetMemoriesResponseIncludedRelatedChildrenItemParams,
    )
    from .get_memories_response_included_related_children_item_document import (
        GetMemoriesResponseIncludedRelatedChildrenItemDocumentParams,
    )
    from .get_memories_response_included_related_children_item_document_system import (
        GetMemoriesResponseIncludedRelatedChildrenItemDocumentSystemParams,
    )
    from .get_memories_response_included_related_children_item_system import (
        GetMemoriesResponseIncludedRelatedChildrenItemSystemParams,
    )
    from .get_memories_response_included_related_parents_item import GetMemoriesResponseIncludedRelatedParentsItemParams
    from .get_memories_response_included_related_parents_item_document import (
        GetMemoriesResponseIncludedRelatedParentsItemDocumentParams,
    )
    from .get_memories_response_included_related_parents_item_document_system import (
        GetMemoriesResponseIncludedRelatedParentsItemDocumentSystemParams,
    )
    from .get_memories_response_included_related_parents_item_system import (
        GetMemoriesResponseIncludedRelatedParentsItemSystemParams,
    )
    from .get_memories_response_included_related_siblings_item import (
        GetMemoriesResponseIncludedRelatedSiblingsItemParams,
    )
    from .get_memories_response_included_related_siblings_item_document import (
        GetMemoriesResponseIncludedRelatedSiblingsItemDocumentParams,
    )
    from .get_memories_response_included_related_siblings_item_document_system import (
        GetMemoriesResponseIncludedRelatedSiblingsItemDocumentSystemParams,
    )
    from .get_memories_response_included_related_siblings_item_system import (
        GetMemoriesResponseIncludedRelatedSiblingsItemSystemParams,
    )
_dynamic_imports: typing.Dict[str, str] = {
    "GetMemoriesResponseIncludedDocumentParams": ".get_memories_response_included_document",
    "GetMemoriesResponseIncludedDocumentSystemParams": ".get_memories_response_included_document_system",
    "GetMemoriesResponseIncludedParams": ".get_memories_response_included",
    "GetMemoriesResponseIncludedRelatedChildrenItemDocumentParams": ".get_memories_response_included_related_children_item_document",
    "GetMemoriesResponseIncludedRelatedChildrenItemDocumentSystemParams": ".get_memories_response_included_related_children_item_document_system",
    "GetMemoriesResponseIncludedRelatedChildrenItemParams": ".get_memories_response_included_related_children_item",
    "GetMemoriesResponseIncludedRelatedChildrenItemSystemParams": ".get_memories_response_included_related_children_item_system",
    "GetMemoriesResponseIncludedRelatedParams": ".get_memories_response_included_related",
    "GetMemoriesResponseIncludedRelatedParentsItemDocumentParams": ".get_memories_response_included_related_parents_item_document",
    "GetMemoriesResponseIncludedRelatedParentsItemDocumentSystemParams": ".get_memories_response_included_related_parents_item_document_system",
    "GetMemoriesResponseIncludedRelatedParentsItemParams": ".get_memories_response_included_related_parents_item",
    "GetMemoriesResponseIncludedRelatedParentsItemSystemParams": ".get_memories_response_included_related_parents_item_system",
    "GetMemoriesResponseIncludedRelatedSiblingsItemDocumentParams": ".get_memories_response_included_related_siblings_item_document",
    "GetMemoriesResponseIncludedRelatedSiblingsItemDocumentSystemParams": ".get_memories_response_included_related_siblings_item_document_system",
    "GetMemoriesResponseIncludedRelatedSiblingsItemParams": ".get_memories_response_included_related_siblings_item",
    "GetMemoriesResponseIncludedRelatedSiblingsItemSystemParams": ".get_memories_response_included_related_siblings_item_system",
    "GetMemoriesResponseParams": ".get_memories_response",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "GetMemoriesResponseIncludedDocumentParams",
    "GetMemoriesResponseIncludedDocumentSystemParams",
    "GetMemoriesResponseIncludedParams",
    "GetMemoriesResponseIncludedRelatedChildrenItemDocumentParams",
    "GetMemoriesResponseIncludedRelatedChildrenItemDocumentSystemParams",
    "GetMemoriesResponseIncludedRelatedChildrenItemParams",
    "GetMemoriesResponseIncludedRelatedChildrenItemSystemParams",
    "GetMemoriesResponseIncludedRelatedParams",
    "GetMemoriesResponseIncludedRelatedParentsItemDocumentParams",
    "GetMemoriesResponseIncludedRelatedParentsItemDocumentSystemParams",
    "GetMemoriesResponseIncludedRelatedParentsItemParams",
    "GetMemoriesResponseIncludedRelatedParentsItemSystemParams",
    "GetMemoriesResponseIncludedRelatedSiblingsItemDocumentParams",
    "GetMemoriesResponseIncludedRelatedSiblingsItemDocumentSystemParams",
    "GetMemoriesResponseIncludedRelatedSiblingsItemParams",
    "GetMemoriesResponseIncludedRelatedSiblingsItemSystemParams",
    "GetMemoriesResponseParams",
]
