# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from .get_memories_response_included_document import GetMemoriesResponseIncludedDocumentParams
from .get_memories_response_included_related import GetMemoriesResponseIncludedRelatedParams


class GetMemoriesResponseIncludedParams(typing_extensions.TypedDict):
    """
    Requested extras
    """

    related: typing_extensions.NotRequired[GetMemoriesResponseIncludedRelatedParams]
    """
    Present when include has related
    """

    document: typing_extensions.NotRequired[GetMemoriesResponseIncludedDocumentParams]
    """
    Source document; present when include has documents and one exists
    """
