# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ...core.serialization import FieldMetadata


class GetMemoriesResponseIncludedRelatedChildrenItemSystemParams(typing_extensions.TypedDict):
    """
    Lifecycle details for the related memory
    """

    updated_at: typing_extensions.Annotated[str, FieldMetadata(alias="updatedAt")]
    """
    ISO 8601 timestamp of the related memory's latest update
    """
