# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from .get_memories_response_included_related_children_item import GetMemoriesResponseIncludedRelatedChildrenItemParams
from .get_memories_response_included_related_parents_item import GetMemoriesResponseIncludedRelatedParentsItemParams
from .get_memories_response_included_related_siblings_item import GetMemoriesResponseIncludedRelatedSiblingsItemParams


class GetMemoriesResponseIncludedRelatedParams(typing_extensions.TypedDict):
    """
    Present when include has related
    """

    parents: typing.Sequence[GetMemoriesResponseIncludedRelatedParentsItemParams]
    """
    Earlier versions this memory updates, nearest first
    """

    children: typing.Sequence[GetMemoriesResponseIncludedRelatedChildrenItemParams]
    """
    Newer versions that update this memory, nearest first
    """

    siblings: typing.Sequence[GetMemoriesResponseIncludedRelatedSiblingsItemParams]
    """
    Memories connected by extends or derives, nearest first
    """
