# This file was auto-generated by Fern from our API Definition.

import typing

import httpx

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..requests.connector_selection import ConnectorSelectionParams
from ..requests.connector_setup import ConnectorSetupParams
from ..types.connector import Connector
from ..types.connector_deleted import ConnectorDeleted
from ..types.connector_list import ConnectorList
from ..types.connector_provider import ConnectorProvider
from ..types.connector_setup_result import ConnectorSetupResult
from ..types.connector_sync_started import ConnectorSyncStarted
from .raw_client import AsyncRawConnectorsClient, RawConnectorsClient
from .types.delete_connectors_request_delete_documents import DeleteConnectorsRequestDeleteDocuments

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ConnectorsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawConnectorsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawConnectorsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawConnectorsClient
        """
        return self._raw_client

    def list_all(
        self,
        *,
        provider: typing.Optional[ConnectorProvider] = None,
        page: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
        extra_headers: typing.Optional[typing.Mapping[str, str]] = None,
        extra_query: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        extra_body: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        timeout: typing.Union[float, httpx.Timeout, None] = None,
    ) -> ConnectorList:
        """
        List connectors across every namespace this key can read. Use it for admin views that span users or projects.

        Parameters
        ----------
        provider : typing.Optional[ConnectorProvider]
            Only return connectors for this provider

        page : typing.Optional[int]
            One-based page number

        limit : typing.Optional[int]
            Maximum connectors to return per page

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ConnectorList
            Connectors across namespaces

        Examples
        --------
        from supermemory import Supermemory

        client = Supermemory(
            api_key="YOUR_API_KEY",
        )
        client.connectors.list_all()
        """
        _response = self._raw_client.list_all(
            provider=provider, page=page, limit=limit, request_options=request_options
        )
        return _response.data

    def list(
        self,
        namespace: str,
        *,
        provider: typing.Optional[ConnectorProvider] = None,
        page: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
        extra_headers: typing.Optional[typing.Mapping[str, str]] = None,
        extra_query: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        extra_body: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        timeout: typing.Union[float, httpx.Timeout, None] = None,
    ) -> ConnectorList:
        """
        List the connectors that sync into this namespace.

        Parameters
        ----------
        namespace : str
            Namespace identifier. This can be an ID for your user, a project ID, or any other identifier you wish to use to scope documents and memories.

        provider : typing.Optional[ConnectorProvider]
            Only return connectors for this provider

        page : typing.Optional[int]
            One-based page number

        limit : typing.Optional[int]
            Maximum connectors to return per page

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ConnectorList
            Connectors in this namespace

        Examples
        --------
        from supermemory import Supermemory

        client = Supermemory(
            api_key="YOUR_API_KEY",
        )
        client.connectors.list(
            namespace="user_alex",
        )
        """
        _response = self._raw_client.list(
            namespace, provider=provider, page=page, limit=limit, request_options=request_options
        )
        return _response.data

    def create(
        self,
        namespace: str,
        *,
        request: ConnectorSetupParams,
        request_options: typing.Optional[RequestOptions] = None,
        extra_headers: typing.Optional[typing.Mapping[str, str]] = None,
        extra_query: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        extra_body: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        timeout: typing.Union[float, httpx.Timeout, None] = None,
    ) -> ConnectorSetupResult:
        """
        Connect an external source to this namespace. OAuth providers return an authUrl to send the user to; providers that authenticate with config start syncing right away.

        Parameters
        ----------
        namespace : str
            Namespace identifier. This can be an ID for your user, a project ID, or any other identifier you wish to use to scope documents and memories.

        request : ConnectorSetupParams

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ConnectorSetupResult
            Connector created

        Examples
        --------
        from supermemory import Supermemory

        client = Supermemory(
            api_key="YOUR_API_KEY",
        )
        client.connectors.create(
            namespace="user_alex",
            request={"provider": "notion"},
        )
        """
        _response = self._raw_client.create(namespace, request=request, request_options=request_options)
        return _response.data

    def get(
        self,
        namespace: str,
        id: str,
        *,
        attach: typing.Optional[str] = None,
        return_url: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
        extra_headers: typing.Optional[typing.Mapping[str, str]] = None,
        extra_query: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        extra_body: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        timeout: typing.Union[float, httpx.Timeout, None] = None,
    ) -> Connector:
        """
        Read one connector. Add attach=syncs to include its recent sync runs and the items that failed. attach=picker needs an admin with write access, since the link changes what syncs.

        Parameters
        ----------
        namespace : str
            Namespace identifier. This can be an ID for your user, a project ID, or any other identifier you wish to use to scope documents and memories.

        id : str
            Connector identifier returned when the connector was created

        attach : typing.Optional[str]
            Comma-separated extras. syncs: the 10 most recent sync runs with their failed items. picker: a one-time hosted picker URL.

        return_url : typing.Optional[str]
            Where the hosted picker sends the user when they finish

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Connector
            Connector

        Examples
        --------
        from supermemory import Supermemory

        client = Supermemory(
            api_key="YOUR_API_KEY",
        )
        client.connectors.get(
            namespace="user_alex",
            id="PTzGiUYei7pgzg5buzZHgA",
        )
        """
        _response = self._raw_client.get(
            namespace, id, attach=attach, return_url=return_url, request_options=request_options
        )
        return _response.data

    def delete(
        self,
        namespace: str,
        id: str,
        *,
        delete_documents: typing.Optional[DeleteConnectorsRequestDeleteDocuments] = None,
        request_options: typing.Optional[RequestOptions] = None,
        extra_headers: typing.Optional[typing.Mapping[str, str]] = None,
        extra_query: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        extra_body: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        timeout: typing.Union[float, httpx.Timeout, None] = None,
    ) -> ConnectorDeleted:
        """
        Disconnect a connector and stop its webhooks. Its imported documents are deleted too unless deleteDocuments is false.

        Parameters
        ----------
        namespace : str
            Namespace identifier. This can be an ID for your user, a project ID, or any other identifier you wish to use to scope documents and memories.

        id : str
            Connector identifier returned when the connector was created

        delete_documents : typing.Optional[DeleteConnectorsRequestDeleteDocuments]
            Also delete documents this connector imported. Defaults to true.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ConnectorDeleted
            Connector deleted

        Examples
        --------
        from supermemory import Supermemory

        client = Supermemory(
            api_key="YOUR_API_KEY",
        )
        client.connectors.delete(
            namespace="user_alex",
            id="PTzGiUYei7pgzg5buzZHgA",
        )
        """
        _response = self._raw_client.delete(
            namespace, id, delete_documents=delete_documents, request_options=request_options
        )
        return _response.data

    def update(
        self,
        namespace: str,
        id: str,
        *,
        selection: typing.Optional[ConnectorSelectionParams] = OMIT,
        document_limit: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
        extra_headers: typing.Optional[typing.Mapping[str, str]] = None,
        extra_query: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        extra_body: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        timeout: typing.Union[float, httpx.Timeout, None] = None,
    ) -> Connector:
        """
        Change what a connector syncs. A new selection replaces the old one and starts a sync.

        Parameters
        ----------
        namespace : str
            Namespace identifier. This can be an ID for your user, a project ID, or any other identifier you wish to use to scope documents and memories.

        id : str
            Connector identifier returned when the connector was created

        selection : typing.Optional[ConnectorSelectionParams]
            What to sync, as ids grouped by kind. GitHub takes repos, Gmail takes labels, Google Drive takes files and folders. Replaces the current selection.

        document_limit : typing.Optional[int]
            Maximum documents this connector imports

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Connector
            Updated connector

        Examples
        --------
        from supermemory import Supermemory

        client = Supermemory(
            api_key="YOUR_API_KEY",
        )
        client.connectors.update(
            namespace="user_alex",
            id="PTzGiUYei7pgzg5buzZHgA",
        )
        """
        _response = self._raw_client.update(
            namespace, id, selection=selection, document_limit=document_limit, request_options=request_options
        )
        return _response.data

    def sync(
        self,
        namespace: str,
        id: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
        extra_headers: typing.Optional[typing.Mapping[str, str]] = None,
        extra_query: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        extra_body: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        timeout: typing.Union[float, httpx.Timeout, None] = None,
    ) -> ConnectorSyncStarted:
        """
        Start a sync now. Returns 409 while a sync for this connector is already running.

        Parameters
        ----------
        namespace : str
            Namespace identifier. This can be an ID for your user, a project ID, or any other identifier you wish to use to scope documents and memories.

        id : str
            Connector identifier returned when the connector was created

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ConnectorSyncStarted
            Sync queued

        Examples
        --------
        from supermemory import Supermemory

        client = Supermemory(
            api_key="YOUR_API_KEY",
        )
        client.connectors.sync(
            namespace="user_alex",
            id="PTzGiUYei7pgzg5buzZHgA",
        )
        """
        _response = self._raw_client.sync(namespace, id, request_options=request_options)
        return _response.data


class AsyncConnectorsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawConnectorsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawConnectorsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawConnectorsClient
        """
        return self._raw_client

    async def list_all(
        self,
        *,
        provider: typing.Optional[ConnectorProvider] = None,
        page: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
        extra_headers: typing.Optional[typing.Mapping[str, str]] = None,
        extra_query: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        extra_body: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        timeout: typing.Union[float, httpx.Timeout, None] = None,
    ) -> ConnectorList:
        """
        List connectors across every namespace this key can read. Use it for admin views that span users or projects.

        Parameters
        ----------
        provider : typing.Optional[ConnectorProvider]
            Only return connectors for this provider

        page : typing.Optional[int]
            One-based page number

        limit : typing.Optional[int]
            Maximum connectors to return per page

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ConnectorList
            Connectors across namespaces

        Examples
        --------
        import asyncio

        from supermemory import AsyncSupermemory

        client = AsyncSupermemory(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.connectors.list_all()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_all(
            provider=provider, page=page, limit=limit, request_options=request_options
        )
        return _response.data

    async def list(
        self,
        namespace: str,
        *,
        provider: typing.Optional[ConnectorProvider] = None,
        page: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
        extra_headers: typing.Optional[typing.Mapping[str, str]] = None,
        extra_query: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        extra_body: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        timeout: typing.Union[float, httpx.Timeout, None] = None,
    ) -> ConnectorList:
        """
        List the connectors that sync into this namespace.

        Parameters
        ----------
        namespace : str
            Namespace identifier. This can be an ID for your user, a project ID, or any other identifier you wish to use to scope documents and memories.

        provider : typing.Optional[ConnectorProvider]
            Only return connectors for this provider

        page : typing.Optional[int]
            One-based page number

        limit : typing.Optional[int]
            Maximum connectors to return per page

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ConnectorList
            Connectors in this namespace

        Examples
        --------
        import asyncio

        from supermemory import AsyncSupermemory

        client = AsyncSupermemory(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.connectors.list(
                namespace="user_alex",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list(
            namespace, provider=provider, page=page, limit=limit, request_options=request_options
        )
        return _response.data

    async def create(
        self,
        namespace: str,
        *,
        request: ConnectorSetupParams,
        request_options: typing.Optional[RequestOptions] = None,
        extra_headers: typing.Optional[typing.Mapping[str, str]] = None,
        extra_query: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        extra_body: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        timeout: typing.Union[float, httpx.Timeout, None] = None,
    ) -> ConnectorSetupResult:
        """
        Connect an external source to this namespace. OAuth providers return an authUrl to send the user to; providers that authenticate with config start syncing right away.

        Parameters
        ----------
        namespace : str
            Namespace identifier. This can be an ID for your user, a project ID, or any other identifier you wish to use to scope documents and memories.

        request : ConnectorSetupParams

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ConnectorSetupResult
            Connector created

        Examples
        --------
        import asyncio

        from supermemory import AsyncSupermemory

        client = AsyncSupermemory(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.connectors.create(
                namespace="user_alex",
                request={"provider": "notion"},
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(namespace, request=request, request_options=request_options)
        return _response.data

    async def get(
        self,
        namespace: str,
        id: str,
        *,
        attach: typing.Optional[str] = None,
        return_url: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
        extra_headers: typing.Optional[typing.Mapping[str, str]] = None,
        extra_query: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        extra_body: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        timeout: typing.Union[float, httpx.Timeout, None] = None,
    ) -> Connector:
        """
        Read one connector. Add attach=syncs to include its recent sync runs and the items that failed. attach=picker needs an admin with write access, since the link changes what syncs.

        Parameters
        ----------
        namespace : str
            Namespace identifier. This can be an ID for your user, a project ID, or any other identifier you wish to use to scope documents and memories.

        id : str
            Connector identifier returned when the connector was created

        attach : typing.Optional[str]
            Comma-separated extras. syncs: the 10 most recent sync runs with their failed items. picker: a one-time hosted picker URL.

        return_url : typing.Optional[str]
            Where the hosted picker sends the user when they finish

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Connector
            Connector

        Examples
        --------
        import asyncio

        from supermemory import AsyncSupermemory

        client = AsyncSupermemory(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.connectors.get(
                namespace="user_alex",
                id="PTzGiUYei7pgzg5buzZHgA",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(
            namespace, id, attach=attach, return_url=return_url, request_options=request_options
        )
        return _response.data

    async def delete(
        self,
        namespace: str,
        id: str,
        *,
        delete_documents: typing.Optional[DeleteConnectorsRequestDeleteDocuments] = None,
        request_options: typing.Optional[RequestOptions] = None,
        extra_headers: typing.Optional[typing.Mapping[str, str]] = None,
        extra_query: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        extra_body: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        timeout: typing.Union[float, httpx.Timeout, None] = None,
    ) -> ConnectorDeleted:
        """
        Disconnect a connector and stop its webhooks. Its imported documents are deleted too unless deleteDocuments is false.

        Parameters
        ----------
        namespace : str
            Namespace identifier. This can be an ID for your user, a project ID, or any other identifier you wish to use to scope documents and memories.

        id : str
            Connector identifier returned when the connector was created

        delete_documents : typing.Optional[DeleteConnectorsRequestDeleteDocuments]
            Also delete documents this connector imported. Defaults to true.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ConnectorDeleted
            Connector deleted

        Examples
        --------
        import asyncio

        from supermemory import AsyncSupermemory

        client = AsyncSupermemory(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.connectors.delete(
                namespace="user_alex",
                id="PTzGiUYei7pgzg5buzZHgA",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(
            namespace, id, delete_documents=delete_documents, request_options=request_options
        )
        return _response.data

    async def update(
        self,
        namespace: str,
        id: str,
        *,
        selection: typing.Optional[ConnectorSelectionParams] = OMIT,
        document_limit: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
        extra_headers: typing.Optional[typing.Mapping[str, str]] = None,
        extra_query: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        extra_body: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        timeout: typing.Union[float, httpx.Timeout, None] = None,
    ) -> Connector:
        """
        Change what a connector syncs. A new selection replaces the old one and starts a sync.

        Parameters
        ----------
        namespace : str
            Namespace identifier. This can be an ID for your user, a project ID, or any other identifier you wish to use to scope documents and memories.

        id : str
            Connector identifier returned when the connector was created

        selection : typing.Optional[ConnectorSelectionParams]
            What to sync, as ids grouped by kind. GitHub takes repos, Gmail takes labels, Google Drive takes files and folders. Replaces the current selection.

        document_limit : typing.Optional[int]
            Maximum documents this connector imports

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Connector
            Updated connector

        Examples
        --------
        import asyncio

        from supermemory import AsyncSupermemory

        client = AsyncSupermemory(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.connectors.update(
                namespace="user_alex",
                id="PTzGiUYei7pgzg5buzZHgA",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(
            namespace, id, selection=selection, document_limit=document_limit, request_options=request_options
        )
        return _response.data

    async def sync(
        self,
        namespace: str,
        id: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
        extra_headers: typing.Optional[typing.Mapping[str, str]] = None,
        extra_query: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        extra_body: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        timeout: typing.Union[float, httpx.Timeout, None] = None,
    ) -> ConnectorSyncStarted:
        """
        Start a sync now. Returns 409 while a sync for this connector is already running.

        Parameters
        ----------
        namespace : str
            Namespace identifier. This can be an ID for your user, a project ID, or any other identifier you wish to use to scope documents and memories.

        id : str
            Connector identifier returned when the connector was created

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ConnectorSyncStarted
            Sync queued

        Examples
        --------
        import asyncio

        from supermemory import AsyncSupermemory

        client = AsyncSupermemory(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.connectors.sync(
                namespace="user_alex",
                id="PTzGiUYei7pgzg5buzZHgA",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.sync(namespace, id, request_options=request_options)
        return _response.data
