# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .bad_request_error_body import BadRequestErrorBodyParams
    from .batch_add_item_result import BatchAddItemResultParams
    from .batch_add_result import BatchAddResultParams
    from .chunk import ChunkParams
    from .chunk_list_item import ChunkListItemParams
    from .chunk_system import ChunkSystemParams
    from .connector import ConnectorParams
    from .connector_capabilities import ConnectorCapabilitiesParams
    from .connector_config_value import ConnectorConfigValueParams
    from .connector_deleted import ConnectorDeletedParams
    from .connector_link import ConnectorLinkParams
    from .connector_list import ConnectorListParams
    from .connector_run import ConnectorRunParams
    from .connector_run_system import ConnectorRunSystemParams
    from .connector_selection import ConnectorSelectionParams
    from .connector_selection_item import ConnectorSelectionItemParams
    from .connector_setup import (
        ConnectorSetupParams,
        ConnectorSetup_GithubParams,
        ConnectorSetup_GmailParams,
        ConnectorSetup_GoogleDriveParams,
        ConnectorSetup_GranolaParams,
        ConnectorSetup_NotionParams,
        ConnectorSetup_OnedriveParams,
        ConnectorSetup_S3Params,
        ConnectorSetup_WebCrawlerParams,
    )
    from .connector_setup_github import ConnectorSetupGithubParams
    from .connector_setup_gmail import ConnectorSetupGmailParams
    from .connector_setup_google_drive import ConnectorSetupGoogleDriveParams
    from .connector_setup_granola import ConnectorSetupGranolaParams
    from .connector_setup_notion import ConnectorSetupNotionParams
    from .connector_setup_onedrive import ConnectorSetupOnedriveParams
    from .connector_setup_result import ConnectorSetupResultParams
    from .connector_setup_s3 import ConnectorSetupS3Params
    from .connector_setup_web_crawler import ConnectorSetupWebCrawlerParams
    from .connector_sync import ConnectorSyncParams
    from .connector_sync_failure import ConnectorSyncFailureParams
    from .connector_sync_started import ConnectorSyncStartedParams
    from .connector_sync_system import ConnectorSyncSystemParams
    from .connector_system import ConnectorSystemParams
    from .delete_document_error import DeleteDocumentErrorParams
    from .delete_documents_result import DeleteDocumentsResultParams
    from .document import DocumentParams
    from .document_input import DocumentInputParams
    from .document_list_item import DocumentListItemParams
    from .document_list_item_system import DocumentListItemSystemParams
    from .document_ref import DocumentRefParams
    from .document_system import DocumentSystemParams
    from .error_response import ErrorResponseParams
    from .filter_and import FilterAndParams
    from .filter_array_contains import FilterArrayContainsParams
    from .filter_expression import FilterExpressionParams
    from .filter_number_compare import FilterNumberCompareParams
    from .filter_or import FilterOrParams
    from .filter_predicate import FilterPredicateParams
    from .filter_string_contains import FilterStringContainsParams
    from .filter_string_equals import FilterStringEqualsParams
    from .filter_value_equals import FilterValueEqualsParams
    from .filter_value_equals_value import FilterValueEqualsValueParams
    from .forget_error import ForgetErrorParams
    from .forget_match import ForgetMatchParams
    from .forget_result import ForgetResultParams
    from .google_drive_config import GoogleDriveConfigParams
    from .granola_config import GranolaConfigParams
    from .list_request_include import ListRequestIncludeParams
    from .list_response import ListResponseParams
    from .memory import MemoryParams
    from .memory_details import MemoryDetailsParams
    from .memory_included import MemoryIncludedParams
    from .memory_included_document import MemoryIncludedDocumentParams
    from .memory_included_document_system import MemoryIncludedDocumentSystemParams
    from .memory_included_related import MemoryIncludedRelatedParams
    from .memory_included_related_children_item import MemoryIncludedRelatedChildrenItemParams
    from .memory_included_related_children_item_document import MemoryIncludedRelatedChildrenItemDocumentParams
    from .memory_included_related_children_item_document_system import (
        MemoryIncludedRelatedChildrenItemDocumentSystemParams,
    )
    from .memory_included_related_children_item_system import MemoryIncludedRelatedChildrenItemSystemParams
    from .memory_included_related_parents_item import MemoryIncludedRelatedParentsItemParams
    from .memory_included_related_parents_item_document import MemoryIncludedRelatedParentsItemDocumentParams
    from .memory_included_related_parents_item_document_system import (
        MemoryIncludedRelatedParentsItemDocumentSystemParams,
    )
    from .memory_included_related_parents_item_system import MemoryIncludedRelatedParentsItemSystemParams
    from .memory_included_related_siblings_item import MemoryIncludedRelatedSiblingsItemParams
    from .memory_included_related_siblings_item_document import MemoryIncludedRelatedSiblingsItemDocumentParams
    from .memory_included_related_siblings_item_document_system import (
        MemoryIncludedRelatedSiblingsItemDocumentSystemParams,
    )
    from .memory_included_related_siblings_item_system import MemoryIncludedRelatedSiblingsItemSystemParams
    from .memory_system import MemorySystemParams
    from .metadata_value import MetadataValueParams
    from .namespace import NamespaceParams
    from .namespace_deleted import NamespaceDeletedParams, NamespaceDeleted_DeletedParams, NamespaceDeleted_QueuedParams
    from .namespace_deleted_deleted import NamespaceDeletedDeletedParams
    from .namespace_deleted_queued import NamespaceDeletedQueuedParams
    from .namespace_details import NamespaceDetailsParams
    from .namespace_list import NamespaceListParams
    from .namespace_system import NamespaceSystemParams
    from .organization import OrganizationParams
    from .pagination import PaginationParams
    from .profile import ProfileParams
    from .profile_buckets import ProfileBucketsParams
    from .profile_fact import ProfileFactParams
    from .profile_response import ProfileResponseParams
    from .related_memories import RelatedMemoriesParams
    from .related_memory import RelatedMemoryParams
    from .related_memory_system import RelatedMemorySystemParams
    from .s3config import S3ConfigParams
    from .search_include import SearchIncludeParams
    from .search_response import SearchResponseParams
    from .search_result import SearchResultParams
    from .search_result_included import SearchResultIncludedParams
    from .search_result_included_document import SearchResultIncludedDocumentParams
    from .search_result_included_document_system import SearchResultIncludedDocumentSystemParams
    from .search_result_system import SearchResultSystemParams
    from .validation_error_response import ValidationErrorResponseParams
    from .validation_error_response_error_item import ValidationErrorResponseErrorItemParams
    from .validation_error_response_error_item_path_item import ValidationErrorResponseErrorItemPathItemParams
    from .web_crawler_config import WebCrawlerConfigParams
_dynamic_imports: typing.Dict[str, str] = {
    "BadRequestErrorBodyParams": ".bad_request_error_body",
    "BatchAddItemResultParams": ".batch_add_item_result",
    "BatchAddResultParams": ".batch_add_result",
    "ChunkListItemParams": ".chunk_list_item",
    "ChunkParams": ".chunk",
    "ChunkSystemParams": ".chunk_system",
    "ConnectorCapabilitiesParams": ".connector_capabilities",
    "ConnectorConfigValueParams": ".connector_config_value",
    "ConnectorDeletedParams": ".connector_deleted",
    "ConnectorLinkParams": ".connector_link",
    "ConnectorListParams": ".connector_list",
    "ConnectorParams": ".connector",
    "ConnectorRunParams": ".connector_run",
    "ConnectorRunSystemParams": ".connector_run_system",
    "ConnectorSelectionItemParams": ".connector_selection_item",
    "ConnectorSelectionParams": ".connector_selection",
    "ConnectorSetupGithubParams": ".connector_setup_github",
    "ConnectorSetupGmailParams": ".connector_setup_gmail",
    "ConnectorSetupGoogleDriveParams": ".connector_setup_google_drive",
    "ConnectorSetupGranolaParams": ".connector_setup_granola",
    "ConnectorSetupNotionParams": ".connector_setup_notion",
    "ConnectorSetupOnedriveParams": ".connector_setup_onedrive",
    "ConnectorSetupParams": ".connector_setup",
    "ConnectorSetupResultParams": ".connector_setup_result",
    "ConnectorSetupS3Params": ".connector_setup_s3",
    "ConnectorSetupWebCrawlerParams": ".connector_setup_web_crawler",
    "ConnectorSetup_GithubParams": ".connector_setup",
    "ConnectorSetup_GmailParams": ".connector_setup",
    "ConnectorSetup_GoogleDriveParams": ".connector_setup",
    "ConnectorSetup_GranolaParams": ".connector_setup",
    "ConnectorSetup_NotionParams": ".connector_setup",
    "ConnectorSetup_OnedriveParams": ".connector_setup",
    "ConnectorSetup_S3Params": ".connector_setup",
    "ConnectorSetup_WebCrawlerParams": ".connector_setup",
    "ConnectorSyncFailureParams": ".connector_sync_failure",
    "ConnectorSyncParams": ".connector_sync",
    "ConnectorSyncStartedParams": ".connector_sync_started",
    "ConnectorSyncSystemParams": ".connector_sync_system",
    "ConnectorSystemParams": ".connector_system",
    "DeleteDocumentErrorParams": ".delete_document_error",
    "DeleteDocumentsResultParams": ".delete_documents_result",
    "DocumentInputParams": ".document_input",
    "DocumentListItemParams": ".document_list_item",
    "DocumentListItemSystemParams": ".document_list_item_system",
    "DocumentParams": ".document",
    "DocumentRefParams": ".document_ref",
    "DocumentSystemParams": ".document_system",
    "ErrorResponseParams": ".error_response",
    "FilterAndParams": ".filter_and",
    "FilterArrayContainsParams": ".filter_array_contains",
    "FilterExpressionParams": ".filter_expression",
    "FilterNumberCompareParams": ".filter_number_compare",
    "FilterOrParams": ".filter_or",
    "FilterPredicateParams": ".filter_predicate",
    "FilterStringContainsParams": ".filter_string_contains",
    "FilterStringEqualsParams": ".filter_string_equals",
    "FilterValueEqualsParams": ".filter_value_equals",
    "FilterValueEqualsValueParams": ".filter_value_equals_value",
    "ForgetErrorParams": ".forget_error",
    "ForgetMatchParams": ".forget_match",
    "ForgetResultParams": ".forget_result",
    "GoogleDriveConfigParams": ".google_drive_config",
    "GranolaConfigParams": ".granola_config",
    "ListRequestIncludeParams": ".list_request_include",
    "ListResponseParams": ".list_response",
    "MemoryDetailsParams": ".memory_details",
    "MemoryIncludedDocumentParams": ".memory_included_document",
    "MemoryIncludedDocumentSystemParams": ".memory_included_document_system",
    "MemoryIncludedParams": ".memory_included",
    "MemoryIncludedRelatedChildrenItemDocumentParams": ".memory_included_related_children_item_document",
    "MemoryIncludedRelatedChildrenItemDocumentSystemParams": ".memory_included_related_children_item_document_system",
    "MemoryIncludedRelatedChildrenItemParams": ".memory_included_related_children_item",
    "MemoryIncludedRelatedChildrenItemSystemParams": ".memory_included_related_children_item_system",
    "MemoryIncludedRelatedParams": ".memory_included_related",
    "MemoryIncludedRelatedParentsItemDocumentParams": ".memory_included_related_parents_item_document",
    "MemoryIncludedRelatedParentsItemDocumentSystemParams": ".memory_included_related_parents_item_document_system",
    "MemoryIncludedRelatedParentsItemParams": ".memory_included_related_parents_item",
    "MemoryIncludedRelatedParentsItemSystemParams": ".memory_included_related_parents_item_system",
    "MemoryIncludedRelatedSiblingsItemDocumentParams": ".memory_included_related_siblings_item_document",
    "MemoryIncludedRelatedSiblingsItemDocumentSystemParams": ".memory_included_related_siblings_item_document_system",
    "MemoryIncludedRelatedSiblingsItemParams": ".memory_included_related_siblings_item",
    "MemoryIncludedRelatedSiblingsItemSystemParams": ".memory_included_related_siblings_item_system",
    "MemoryParams": ".memory",
    "MemorySystemParams": ".memory_system",
    "MetadataValueParams": ".metadata_value",
    "NamespaceDeletedDeletedParams": ".namespace_deleted_deleted",
    "NamespaceDeletedParams": ".namespace_deleted",
    "NamespaceDeletedQueuedParams": ".namespace_deleted_queued",
    "NamespaceDeleted_DeletedParams": ".namespace_deleted",
    "NamespaceDeleted_QueuedParams": ".namespace_deleted",
    "NamespaceDetailsParams": ".namespace_details",
    "NamespaceListParams": ".namespace_list",
    "NamespaceParams": ".namespace",
    "NamespaceSystemParams": ".namespace_system",
    "OrganizationParams": ".organization",
    "PaginationParams": ".pagination",
    "ProfileBucketsParams": ".profile_buckets",
    "ProfileFactParams": ".profile_fact",
    "ProfileParams": ".profile",
    "ProfileResponseParams": ".profile_response",
    "RelatedMemoriesParams": ".related_memories",
    "RelatedMemoryParams": ".related_memory",
    "RelatedMemorySystemParams": ".related_memory_system",
    "S3ConfigParams": ".s3config",
    "SearchIncludeParams": ".search_include",
    "SearchResponseParams": ".search_response",
    "SearchResultIncludedDocumentParams": ".search_result_included_document",
    "SearchResultIncludedDocumentSystemParams": ".search_result_included_document_system",
    "SearchResultIncludedParams": ".search_result_included",
    "SearchResultParams": ".search_result",
    "SearchResultSystemParams": ".search_result_system",
    "ValidationErrorResponseErrorItemParams": ".validation_error_response_error_item",
    "ValidationErrorResponseErrorItemPathItemParams": ".validation_error_response_error_item_path_item",
    "ValidationErrorResponseParams": ".validation_error_response",
    "WebCrawlerConfigParams": ".web_crawler_config",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "BadRequestErrorBodyParams",
    "BatchAddItemResultParams",
    "BatchAddResultParams",
    "ChunkListItemParams",
    "ChunkParams",
    "ChunkSystemParams",
    "ConnectorCapabilitiesParams",
    "ConnectorConfigValueParams",
    "ConnectorDeletedParams",
    "ConnectorLinkParams",
    "ConnectorListParams",
    "ConnectorParams",
    "ConnectorRunParams",
    "ConnectorRunSystemParams",
    "ConnectorSelectionItemParams",
    "ConnectorSelectionParams",
    "ConnectorSetupGithubParams",
    "ConnectorSetupGmailParams",
    "ConnectorSetupGoogleDriveParams",
    "ConnectorSetupGranolaParams",
    "ConnectorSetupNotionParams",
    "ConnectorSetupOnedriveParams",
    "ConnectorSetupParams",
    "ConnectorSetupResultParams",
    "ConnectorSetupS3Params",
    "ConnectorSetupWebCrawlerParams",
    "ConnectorSetup_GithubParams",
    "ConnectorSetup_GmailParams",
    "ConnectorSetup_GoogleDriveParams",
    "ConnectorSetup_GranolaParams",
    "ConnectorSetup_NotionParams",
    "ConnectorSetup_OnedriveParams",
    "ConnectorSetup_S3Params",
    "ConnectorSetup_WebCrawlerParams",
    "ConnectorSyncFailureParams",
    "ConnectorSyncParams",
    "ConnectorSyncStartedParams",
    "ConnectorSyncSystemParams",
    "ConnectorSystemParams",
    "DeleteDocumentErrorParams",
    "DeleteDocumentsResultParams",
    "DocumentInputParams",
    "DocumentListItemParams",
    "DocumentListItemSystemParams",
    "DocumentParams",
    "DocumentRefParams",
    "DocumentSystemParams",
    "ErrorResponseParams",
    "FilterAndParams",
    "FilterArrayContainsParams",
    "FilterExpressionParams",
    "FilterNumberCompareParams",
    "FilterOrParams",
    "FilterPredicateParams",
    "FilterStringContainsParams",
    "FilterStringEqualsParams",
    "FilterValueEqualsParams",
    "FilterValueEqualsValueParams",
    "ForgetErrorParams",
    "ForgetMatchParams",
    "ForgetResultParams",
    "GoogleDriveConfigParams",
    "GranolaConfigParams",
    "ListRequestIncludeParams",
    "ListResponseParams",
    "MemoryDetailsParams",
    "MemoryIncludedDocumentParams",
    "MemoryIncludedDocumentSystemParams",
    "MemoryIncludedParams",
    "MemoryIncludedRelatedChildrenItemDocumentParams",
    "MemoryIncludedRelatedChildrenItemDocumentSystemParams",
    "MemoryIncludedRelatedChildrenItemParams",
    "MemoryIncludedRelatedChildrenItemSystemParams",
    "MemoryIncludedRelatedParams",
    "MemoryIncludedRelatedParentsItemDocumentParams",
    "MemoryIncludedRelatedParentsItemDocumentSystemParams",
    "MemoryIncludedRelatedParentsItemParams",
    "MemoryIncludedRelatedParentsItemSystemParams",
    "MemoryIncludedRelatedSiblingsItemDocumentParams",
    "MemoryIncludedRelatedSiblingsItemDocumentSystemParams",
    "MemoryIncludedRelatedSiblingsItemParams",
    "MemoryIncludedRelatedSiblingsItemSystemParams",
    "MemoryParams",
    "MemorySystemParams",
    "MetadataValueParams",
    "NamespaceDeletedDeletedParams",
    "NamespaceDeletedParams",
    "NamespaceDeletedQueuedParams",
    "NamespaceDeleted_DeletedParams",
    "NamespaceDeleted_QueuedParams",
    "NamespaceDetailsParams",
    "NamespaceListParams",
    "NamespaceParams",
    "NamespaceSystemParams",
    "OrganizationParams",
    "PaginationParams",
    "ProfileBucketsParams",
    "ProfileFactParams",
    "ProfileParams",
    "ProfileResponseParams",
    "RelatedMemoriesParams",
    "RelatedMemoryParams",
    "RelatedMemorySystemParams",
    "S3ConfigParams",
    "SearchIncludeParams",
    "SearchResponseParams",
    "SearchResultIncludedDocumentParams",
    "SearchResultIncludedDocumentSystemParams",
    "SearchResultIncludedParams",
    "SearchResultParams",
    "SearchResultSystemParams",
    "ValidationErrorResponseErrorItemParams",
    "ValidationErrorResponseErrorItemPathItemParams",
    "ValidationErrorResponseParams",
    "WebCrawlerConfigParams",
]
