# This file was auto-generated by Fern from our API Definition.

import typing

from .error_response import ErrorResponseParams
from .validation_error_response import ValidationErrorResponseParams

BadRequestErrorBodyParams = typing.Union[ErrorResponseParams, ValidationErrorResponseParams]
