# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from .chunk_system import ChunkSystemParams


class ChunkParams(typing_extensions.TypedDict):
    """
    A chunk of source content belonging to a document
    """

    id: str
    """
    Stable chunk identifier
    """

    position: int
    """
    Zero-based order within the document
    """

    content: str
    """
    Chunk text used for retrieval
    """

    type: str
    """
    Chunk content type
    """

    metadata: typing.Dict[str, typing.Any]
    """
    Chunk metadata; empty object when none
    """

    system: ChunkSystemParams
    """
    Lifecycle timestamps maintained by Supermemory
    """
