# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from ..core.serialization import FieldMetadata
from .chunk_system import ChunkSystemParams


class ChunkListItemParams(typing_extensions.TypedDict):
    id: str
    """
    Stable chunk identifier
    """

    position: int
    """
    Zero-based order within the document
    """

    content: str
    """
    Chunk text used for retrieval
    """

    type: str
    """
    Chunk content type
    """

    metadata: typing.Optional[typing.Dict[str, typing.Any]]
    """
    Chunk metadata, when available
    """

    system: ChunkSystemParams
    """
    Lifecycle timestamps maintained by Supermemory
    """

    document_id: typing_extensions.Annotated[str, FieldMetadata(alias="documentId")]
    """
    ID of the chunk's parent document
    """
