# This file was auto-generated by Fern from our API Definition.

import datetime as dt

import typing_extensions
from ..core.serialization import FieldMetadata


class ChunkSystemParams(typing_extensions.TypedDict):
    """
    Lifecycle timestamps maintained by Supermemory
    """

    created_at: typing_extensions.Annotated[dt.datetime, FieldMetadata(alias="createdAt")]
    """
    ISO 8601 timestamp when the chunk was created
    """
