# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import typing_extensions
from ..core.serialization import FieldMetadata
from ..types.connector_run_status import ConnectorRunStatus


class ConnectorRunSystemParams(typing_extensions.TypedDict):
    """
    Run status and timestamps maintained by Supermemory
    """

    status: ConnectorRunStatus
    started_at: typing_extensions.Annotated[dt.datetime, FieldMetadata(alias="startedAt")]
    """
    ISO 8601 timestamp when the run started
    """

    completed_at: typing_extensions.Annotated[typing.Optional[dt.datetime], FieldMetadata(alias="completedAt")]
    """
    ISO 8601 timestamp when the run ended; null while running
    """
