# This file was auto-generated by Fern from our API Definition.

import datetime as dt

import typing_extensions
from ..core.serialization import FieldMetadata


class ConnectorLinkParams(typing_extensions.TypedDict):
    url: str
    """
    Send the user here to choose what syncs. Works once, in any browser.
    """

    expires_at: typing_extensions.Annotated[dt.datetime, FieldMetadata(alias="expiresAt")]
