# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ..core.serialization import FieldMetadata


class ConnectorSetupGithubParams(typing_extensions.TypedDict):
    redirect_url: typing_extensions.NotRequired[typing_extensions.Annotated[str, FieldMetadata(alias="redirectUrl")]]
    """
    Where the user returns after authorizing with the provider
    """

    document_limit: typing_extensions.NotRequired[
        typing_extensions.Annotated[int, FieldMetadata(alias="documentLimit")]
    ]
    """
    Maximum documents this connector imports
    """
