# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from ..core.serialization import FieldMetadata
from ..types.connector_provider import ConnectorProvider
from .connector_capabilities import ConnectorCapabilitiesParams
from .connector_config_value import ConnectorConfigValueParams
from .connector_link import ConnectorLinkParams
from .connector_run import ConnectorRunParams
from .connector_selection_item import ConnectorSelectionItemParams
from .connector_sync import ConnectorSyncParams
from .connector_system import ConnectorSystemParams


class ConnectorParams(typing_extensions.TypedDict):
    id: str
    provider: ConnectorProvider
    """
    External source
    """

    authorization: typing_extensions.NotRequired[ConnectorLinkParams]
    """
    Present while pending, when the caller can create connectors in this namespace
    """

    namespace: typing.Optional[str]
    """
    Namespace the connector syncs into. Null only for connectors created before namespaces were required.
    """

    account: typing.Optional[str]
    """
    Account on the provider side, usually an email
    """

    capabilities: ConnectorCapabilitiesParams
    config: typing.Optional[typing.Dict[str, typing.Optional[ConnectorConfigValueParams]]]
    """
    Non-secret setup, such as the S3 bucket, crawler start URL or Notion workspace. Credentials are never returned.
    """

    selection: typing.Optional[typing.Dict[str, typing.Optional[typing.Sequence[ConnectorSelectionItemParams]]]]
    """
    What syncs, grouped by kind, in the same shape PATCH takes. Null for connectors that sync everything.
    """

    document_limit: typing_extensions.Annotated[float, FieldMetadata(alias="documentLimit")]
    document_count: typing_extensions.Annotated[float, FieldMetadata(alias="documentCount")]
    latest_run: typing_extensions.Annotated[typing.Optional[ConnectorRunParams], FieldMetadata(alias="latestRun")]
    """
    The most recent sync run, which may still be running or may have failed
    """

    system: ConnectorSystemParams
    """
    Lifecycle status and timestamps maintained by Supermemory
    """

    syncs: typing_extensions.NotRequired[typing.Sequence[ConnectorSyncParams]]
    """
    Present when include=syncs
    """

    picker: typing_extensions.NotRequired[typing.Optional[ConnectorLinkParams]]
    """
    Present when include=picker. Null for connectors that sync everything.
    """
