# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from ..core.serialization import FieldMetadata


class ConnectorSyncFailureParams(typing_extensions.TypedDict):
    document_id: typing_extensions.Annotated[str, FieldMetadata(alias="documentId")]
    title: typing.Optional[str]
    error_code: typing_extensions.Annotated[str, FieldMetadata(alias="errorCode")]
    error_message: typing_extensions.Annotated[str, FieldMetadata(alias="errorMessage")]
    failed_at: typing_extensions.Annotated[str, FieldMetadata(alias="failedAt")]
