# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions


class ConnectorSelectionParams(typing_extensions.TypedDict):
    """
    What to sync, as ids grouped by kind. GitHub takes repos, Gmail takes labels, Google Drive takes files and folders. Replaces the current selection.
    """

    repos: typing_extensions.NotRequired[typing.Sequence[str]]
    """
    GitHub repository ids
    """

    labels: typing_extensions.NotRequired[typing.Sequence[str]]
    """
    Gmail label ids
    """

    files: typing_extensions.NotRequired[typing.Sequence[str]]
    """
    Google Drive file ids
    """

    folders: typing_extensions.NotRequired[typing.Sequence[str]]
    """
    Google Drive folder ids
    """
