# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from ..core.serialization import FieldMetadata
from ..types.connector_error_code import ConnectorErrorCode
from .connector_run_system import ConnectorRunSystemParams


class ConnectorRunParams(typing_extensions.TypedDict):
    error_code: typing_extensions.Annotated[typing.Optional[ConnectorErrorCode], FieldMetadata(alias="errorCode")]
    error: typing.Optional[str]
    """
    Customer-safe error message
    """

    system: ConnectorRunSystemParams
    """
    Run status and timestamps maintained by Supermemory
    """
