# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import typing_extensions
from ..core.serialization import FieldMetadata
from ..types.connector_status import ConnectorStatus


class ConnectorSystemParams(typing_extensions.TypedDict):
    """
    Lifecycle status and timestamps maintained by Supermemory
    """

    status: ConnectorStatus
    """
    pending_authorization until the user finishes the provider login at authorization.url; DELETE cancels it. Pending connectors are not listed.
    """

    created_at: typing_extensions.Annotated[dt.datetime, FieldMetadata(alias="createdAt")]
    """
    ISO 8601 timestamp when the connector was created
    """

    last_successful_sync_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime], FieldMetadata(alias="lastSuccessfulSyncAt")
    ]
    """
    ISO 8601 timestamp when content last finished syncing successfully
    """
