# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions


class ConnectorDeletedParams(typing_extensions.TypedDict):
    id: str
    deleted: typing.Literal[True]
