# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ..core.serialization import FieldMetadata
from .granola_config import GranolaConfigParams


class ConnectorSetupGranolaParams(typing_extensions.TypedDict):
    config: GranolaConfigParams
    """
    Granola API key. Stored encrypted and never returned.
    """

    document_limit: typing_extensions.NotRequired[
        typing_extensions.Annotated[int, FieldMetadata(alias="documentLimit")]
    ]
    """
    Maximum documents this connector imports
    """
