# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ..core.serialization import FieldMetadata
from .s3config import S3ConfigParams


class ConnectorSetupS3Params(typing_extensions.TypedDict):
    config: S3ConfigParams
    """
    S3 bucket to sync. Credentials are stored encrypted and never returned.
    """

    document_limit: typing_extensions.NotRequired[
        typing_extensions.Annotated[int, FieldMetadata(alias="documentLimit")]
    ]
    """
    Maximum documents this connector imports
    """
