# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from ..core.serialization import FieldMetadata
from ..types.connector_error_code import ConnectorErrorCode
from ..types.connector_sync_trigger import ConnectorSyncTrigger
from .connector_sync_failure import ConnectorSyncFailureParams
from .connector_sync_system import ConnectorSyncSystemParams


class ConnectorSyncParams(typing_extensions.TypedDict):
    error_code: typing_extensions.Annotated[typing.Optional[ConnectorErrorCode], FieldMetadata(alias="errorCode")]
    error: typing.Optional[str]
    """
    Customer-safe error message
    """

    system: ConnectorSyncSystemParams
    """
    Run status and timestamps maintained by Supermemory
    """

    id: str
    trigger: ConnectorSyncTrigger
    items_processed: typing_extensions.Annotated[float, FieldMetadata(alias="itemsProcessed")]
    items_failed: typing_extensions.Annotated[float, FieldMetadata(alias="itemsFailed")]
    failures: typing.Sequence[ConnectorSyncFailureParams]
    """
    Failed items, capped. itemsFailed is the true count.
    """
