# This file was auto-generated by Fern from our API Definition.

import typing_extensions


class DeleteDocumentErrorParams(typing_extensions.TypedDict):
    id: str
    """
    The requested document identifier
    """

    error: str
    """
    Why this document could not be deleted
    """
