# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from ..core.serialization import FieldMetadata
from .metadata_value import MetadataValueParams


class DocumentInputParams(typing_extensions.TypedDict):
    content: str
    """
    The content to process. This may be plaintext or a URL to supported rich content.
    """

    id: typing_extensions.NotRequired[str]
    """
    An optional caller-defined document ID
    """

    supporting_context: typing_extensions.NotRequired[
        typing_extensions.Annotated[str, FieldMetadata(alias="supportingContext")]
    ]
    """
    Context used to guide memory extraction within this namespace. Max 1500 characters.
    """

    metadata: typing_extensions.NotRequired[typing.Dict[str, MetadataValueParams]]
    """
    Arbitrary metadata attached to the document and derived data
    """

    group: typing_extensions.NotRequired[typing.Dict[str, MetadataValueParams]]
    """
    Metadata values that isolate related context within the namespace
    """

    date: typing_extensions.NotRequired[str]
    """
    When the source content is from, in ISO 8601 format
    """
