# This file was auto-generated by Fern from our API Definition.

import typing_extensions


class DocumentRefParams(typing_extensions.TypedDict):
    id: str
    """
    Unique identifier of the document
    """

    status: str
    """
    Status of the document
    """
