# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ..types.document_ref_status import DocumentRefStatus


class DocumentRefParams(typing_extensions.TypedDict):
    id: str
    """
    Document identifier to poll or retrieve
    """

    status: DocumentRefStatus
    """
    The document's processing state after this request. queued when new work was queued; otherwise its current state, e.g. done for an unchanged duplicate or failed for a metadata-only update to a failed document.
    """
