# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from .chunk import ChunkParams
from .document_system import DocumentSystemParams
from .memory import MemoryParams


class DocumentParams(typing_extensions.TypedDict):
    """
    Namespace-scoped document. Included keys are omitted unless requested and are empty arrays when requested without results.
    """

    id: str
    """
    Stable document identifier
    """

    title: typing.Optional[str]
    """
    Extracted or caller-provided document title
    """

    type: str
    """
    Detected source or content type
    """

    summary: typing.Optional[str]
    """
    Generated summary of the document, when available
    """

    content: typing.Optional[str]
    """
    Canonical extracted text used for processing and recall
    """

    metadata: typing.Dict[str, typing.Any]
    """
    Caller metadata with internal fields removed
    """

    system: DocumentSystemParams
    """
    Processing status, lifecycle timestamps, and storage path maintained by Supermemory
    """

    chunks: typing_extensions.NotRequired[typing.Sequence[ChunkParams]]
    """
    Ordered document chunks; included only when requested
    """

    memories: typing_extensions.NotRequired[typing.Sequence[MemoryParams]]
    """
    Memories derived from the document; included only when requested
    """
