# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ..types.filter_number_compare_operator import FilterNumberCompareOperator


class FilterNumberCompareParams(typing_extensions.TypedDict):
    field: str
    """
    Metadata key to evaluate, matched literally. A period is part of the key name, not a path into nested metadata.
    """

    operator: FilterNumberCompareOperator
    """
    Numeric comparison to apply
    """

    value: float
    """
    Numeric value to compare against
    """
