# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import typing_extensions

if typing.TYPE_CHECKING:
    from .filter_expression import FilterExpressionParams


class FilterAndParams(typing_extensions.TypedDict):
    operator: typing.Literal["and"]
    """
    Require every nested filter expression to match
    """

    operands: typing.Sequence["FilterExpressionParams"]
    """
    Filter expressions combined with logical AND
    """
