# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ..types.filter_array_contains_operator import FilterArrayContainsOperator


class FilterArrayContainsParams(typing_extensions.TypedDict):
    field: str
    """
    Metadata key to evaluate, matched literally. A period is part of the key name, not a path into nested metadata.
    """

    operator: FilterArrayContainsOperator
    """
    Require or exclude an exact array member
    """

    value: str
    """
    Array member to look for
    """
