# This file was auto-generated by Fern from our API Definition.

import typing_extensions


class ForgetMatchParams(typing_extensions.TypedDict):
    id: str
    """
    Stable identifier of the matched memory
    """

    memory: str
    """
    Matched memory text
    """
