# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ..core.serialization import FieldMetadata
from ..types.google_drive_config_sync_scope import GoogleDriveConfigSyncScope


class GoogleDriveConfigParams(typing_extensions.TypedDict):
    sync_scope: typing_extensions.NotRequired[
        typing_extensions.Annotated[GoogleDriveConfigSyncScope, FieldMetadata(alias="syncScope")]
    ]
    """
    selected (default) syncs only files the user picks. full syncs the whole Drive.
    """
