# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from ..core.serialization import FieldMetadata


class GranolaConfigParams(typing_extensions.TypedDict):
    """
    Granola API key. Stored encrypted and never returned.
    """

    api_key: typing_extensions.Annotated[str, FieldMetadata(alias="apiKey")]
