# This file was auto-generated by Fern from our API Definition.

import typing_extensions


class ListRequestIncludeParams(typing_extensions.TypedDict):
    """
    Optional extras
    """

    forgotten: typing_extensions.NotRequired[bool]
    """
    List forgotten and expired memories too, with isForgotten: true. Applies to type memories only.
    """
