# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from .memory_included_document import MemoryIncludedDocumentParams
from .memory_included_related import MemoryIncludedRelatedParams


class MemoryIncludedParams(typing_extensions.TypedDict):
    """
    Requested extras
    """

    related: typing_extensions.NotRequired[MemoryIncludedRelatedParams]
    """
    Present when include has related
    """

    document: typing_extensions.NotRequired[MemoryIncludedDocumentParams]
    """
    Source document; present when include has documents and one exists
    """
