# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from .memory_included_related_parents_item_document_system import MemoryIncludedRelatedParentsItemDocumentSystemParams


class MemoryIncludedRelatedParentsItemDocumentParams(typing_extensions.TypedDict):
    """
    Source document; present when include has both related and documents
    """

    id: str
    """
    Source document identifier
    """

    title: typing.Optional[str]
    """
    Source document title
    """

    type: typing.Optional[str]
    """
    Detected source or content type
    """

    metadata: typing.Dict[str, typing.Any]
    """
    Public metadata attached to the source document
    """

    summary: typing.Optional[str]
    """
    Generated summary of the source document
    """

    system: MemoryIncludedRelatedParentsItemDocumentSystemParams
    """
    Lifecycle timestamps maintained by Supermemory
    """
