# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from ..core.serialization import FieldMetadata
from .memory_system import MemorySystemParams


class MemoryParams(typing_extensions.TypedDict):
    """
    A memory formed from documents in this namespace
    """

    id: str
    """
    Stable memory identifier
    """

    memory: str
    """
    Learned fact or context extracted from the document
    """

    metadata: typing.Dict[str, typing.Any]
    """
    Memory metadata, including temporal context; empty object when none
    """

    is_static: typing_extensions.Annotated[bool, FieldMetadata(alias="isStatic")]
    """
    Whether the memory belongs to the stable profile section
    """

    is_inference: typing_extensions.Annotated[bool, FieldMetadata(alias="isInference")]
    """
    Whether the memory was inferred rather than explicitly stated
    """

    is_latest: typing_extensions.Annotated[bool, FieldMetadata(alias="isLatest")]
    """
    Whether this is the newest version in its memory chain
    """

    is_forgotten: typing_extensions.Annotated[bool, FieldMetadata(alias="isForgotten")]
    """
    Whether this memory has been excluded from normal recall
    """

    version: int
    """
    Version number within the memory chain
    """

    system: MemorySystemParams
    """
    Lifecycle timestamps maintained by Supermemory
    """
