# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from ..core.serialization import FieldMetadata


class NamespaceDeletedQueuedParams(typing_extensions.TypedDict):
    success: typing.Literal[True]
    """
    Confirms the namespace move was accepted
    """

    operation_id: typing_extensions.Annotated[str, FieldMetadata(alias="operationId")]
    """
    Identifier used to trace the asynchronous move operation
    """

    namespace: str
    """
    Source namespace being removed
    """

    move_to: typing_extensions.Annotated[str, FieldMetadata(alias="moveTo")]
    """
    Destination namespace receiving the content
    """
