# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from ..core.serialization import FieldMetadata
from .namespace_details_system import NamespaceDetailsSystemParams


class NamespaceDetailsParams(typing_extensions.TypedDict):
    namespace: str
    """
    Namespace identifier used in API paths
    """

    supporting_context: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="supportingContext")]
    """
    Background that helps Supermemory interpret documents and form better memories in this namespace
    """

    system: NamespaceDetailsSystemParams
    """
    Namespace lifecycle timestamps
    """
