# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import typing_extensions
from ..core.serialization import FieldMetadata


class NamespaceDeleted_DeletedParams(typing_extensions.TypedDict):
    status: typing.Literal["deleted"]
    namespace: str
    deleted_documents_count: typing_extensions.Annotated[int, FieldMetadata(alias="deletedDocumentsCount")]
    deleted_memories_count: typing_extensions.Annotated[int, FieldMetadata(alias="deletedMemoriesCount")]


class NamespaceDeleted_QueuedParams(typing_extensions.TypedDict):
    status: typing.Literal["queued"]
    operation_id: typing_extensions.Annotated[str, FieldMetadata(alias="operationId")]
    namespace: str
    move_to: typing_extensions.Annotated[str, FieldMetadata(alias="moveTo")]


NamespaceDeletedParams = typing.Union[NamespaceDeleted_DeletedParams, NamespaceDeleted_QueuedParams]
