# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from ..core.serialization import FieldMetadata


class OrganizationParams(typing_extensions.TypedDict):
    organizational_context: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="organizationalContext")
    ]
    """
    Shared background that helps Supermemory interpret content consistently across every namespace
    """

    namespace_count: typing_extensions.Annotated[int, FieldMetadata(alias="namespaceCount")]
    """
    Number of namespaces in the organization
    """
