# This file was auto-generated by Fern from our API Definition.

import typing_extensions
from .profile import ProfileParams


class ProfileResponseParams(typing_extensions.TypedDict):
    profile: ProfileParams
    """
    Continuously maintained understanding of the subject represented by this namespace
    """
