# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from ..types.memory_relation import MemoryRelation
from .related_memory_system import RelatedMemorySystemParams


class RelatedMemoryParams(typing_extensions.TypedDict):
    relation: MemoryRelation
    """
    How this memory is connected to the matched memory
    """

    version: typing_extensions.NotRequired[typing.Optional[float]]
    """
    Version number within the related memory's history
    """

    memory: str
    """
    Related learned fact or context
    """

    metadata: typing_extensions.NotRequired[typing.Optional[typing.Dict[str, typing.Any]]]
    """
    Public metadata associated with the related memory
    """

    system: RelatedMemorySystemParams
    """
    Lifecycle details for the related memory
    """
