# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from ..core.serialization import FieldMetadata
from .search_result import SearchResultParams


class SearchResponseParams(typing_extensions.TypedDict):
    results: typing.Sequence[SearchResultParams]
    """
    Ranked memories and source chunks matching the query
    """

    search_time: typing_extensions.Annotated[float, FieldMetadata(alias="searchTime")]
    """
    Server-side search duration in milliseconds
    """
