# This file was auto-generated by Fern from our API Definition.

import typing_extensions


class SearchIncludeParams(typing_extensions.TypedDict):
    """
    Optional context to include alongside each matching result
    """

    documents: typing_extensions.NotRequired[bool]
    """
    Include the source document for each result when one is available
    """

    related: typing_extensions.NotRequired[bool]
    """
    Include parent, child, and sibling memories that explain how each memory evolved
    """

    forgotten: typing_extensions.NotRequired[bool]
    """
    Let forgotten and expired memories appear in results
    """
