# This file was auto-generated by Fern from our API Definition.

import typing

import httpx

from supermemory._types import NOT_GIVEN, NotGiven

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.profile_buckets import ProfileBuckets
from .raw_client import AsyncRawProfilesClient, RawProfilesClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ProfilesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawProfilesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawProfilesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawProfilesClient
        """
        return self._raw_client

    def get_buckets(
        self,
        namespace: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
        extra_headers: typing.Optional[typing.Mapping[str, str]] = None,
        extra_query: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        extra_body: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        timeout: typing.Union[float, httpx.Timeout, None, NotGiven] = NOT_GIVEN,
    ) -> ProfileBuckets:
        """
        Inspect the profile taxonomy active in this namespace. The response combines organization-wide buckets with namespace-owned additions as a concise name-to-description map.

        Parameters
        ----------
        namespace : str
            The isolated namespace to search. This can be an ID for your user, a project ID, or any other identifier you wish to use to scope memories.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ProfileBuckets
            Effective namespace profile bucket definitions

        Examples
        --------
        from supermemory import Supermemory

        client = Supermemory(
            api_key="YOUR_API_KEY",
        )
        client.profiles.get_buckets(
            namespace="user_alex",
        )
        """
        _response = self._raw_client.get_buckets(namespace, request_options=request_options)
        return _response.data

    def set_buckets(
        self,
        namespace: str,
        *,
        buckets: typing.Dict[str, str],
        request_options: typing.Optional[RequestOptions] = None,
        extra_headers: typing.Optional[typing.Mapping[str, str]] = None,
        extra_query: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        extra_body: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        timeout: typing.Union[float, httpx.Timeout, None, NotGiven] = NOT_GIVEN,
    ) -> ProfileBuckets:
        """
        Teach Supermemory new ways to organize this namespace's profile, or refine how existing namespace-owned buckets are classified. Omitted buckets remain unchanged and organization-wide buckets stay protected.

        Parameters
        ----------
        namespace : str
            The isolated namespace to search. This can be an ID for your user, a project ID, or any other identifier you wish to use to scope memories.

        buckets : typing.Dict[str, str]
            Namespace-owned bucket names mapped to descriptions that guide memory classification. Existing names are updated; new names are added.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ProfileBuckets
            Updated effective namespace profile bucket definitions

        Examples
        --------
        from supermemory import Supermemory

        client = Supermemory(
            api_key="YOUR_API_KEY",
        )
        client.profiles.set_buckets(
            namespace="user_alex",
            buckets={"interests": "Topics the subject actively follows"},
        )
        """
        _response = self._raw_client.set_buckets(namespace, buckets=buckets, request_options=request_options)
        return _response.data

    def delete_buckets(
        self,
        namespace: str,
        *,
        buckets: typing.Sequence[str],
        request_options: typing.Optional[RequestOptions] = None,
        extra_headers: typing.Optional[typing.Mapping[str, str]] = None,
        extra_query: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        extra_body: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        timeout: typing.Union[float, httpx.Timeout, None, NotGiven] = NOT_GIVEN,
    ) -> ProfileBuckets:
        """
        Remove profile categories created specifically for this namespace. Unknown names are safely ignored, while organization-wide buckets remain protected.

        Parameters
        ----------
        namespace : str
            The isolated namespace to search. This can be an ID for your user, a project ID, or any other identifier you wish to use to scope memories.

        buckets : typing.Sequence[str]
            Namespace-owned bucket names to delete. Organization-level buckets are protected and cannot be removed here.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ProfileBuckets
            Updated effective namespace profile bucket definitions

        Examples
        --------
        from supermemory import Supermemory

        client = Supermemory(
            api_key="YOUR_API_KEY",
        )
        client.profiles.delete_buckets(
            namespace="user_alex",
            buckets=["interests"],
        )
        """
        _response = self._raw_client.delete_buckets(namespace, buckets=buckets, request_options=request_options)
        return _response.data


class AsyncProfilesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawProfilesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawProfilesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawProfilesClient
        """
        return self._raw_client

    async def get_buckets(
        self,
        namespace: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
        extra_headers: typing.Optional[typing.Mapping[str, str]] = None,
        extra_query: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        extra_body: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        timeout: typing.Union[float, httpx.Timeout, None, NotGiven] = NOT_GIVEN,
    ) -> ProfileBuckets:
        """
        Inspect the profile taxonomy active in this namespace. The response combines organization-wide buckets with namespace-owned additions as a concise name-to-description map.

        Parameters
        ----------
        namespace : str
            The isolated namespace to search. This can be an ID for your user, a project ID, or any other identifier you wish to use to scope memories.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ProfileBuckets
            Effective namespace profile bucket definitions

        Examples
        --------
        import asyncio

        from supermemory import AsyncSupermemory

        client = AsyncSupermemory(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.profiles.get_buckets(
                namespace="user_alex",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_buckets(namespace, request_options=request_options)
        return _response.data

    async def set_buckets(
        self,
        namespace: str,
        *,
        buckets: typing.Dict[str, str],
        request_options: typing.Optional[RequestOptions] = None,
        extra_headers: typing.Optional[typing.Mapping[str, str]] = None,
        extra_query: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        extra_body: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        timeout: typing.Union[float, httpx.Timeout, None, NotGiven] = NOT_GIVEN,
    ) -> ProfileBuckets:
        """
        Teach Supermemory new ways to organize this namespace's profile, or refine how existing namespace-owned buckets are classified. Omitted buckets remain unchanged and organization-wide buckets stay protected.

        Parameters
        ----------
        namespace : str
            The isolated namespace to search. This can be an ID for your user, a project ID, or any other identifier you wish to use to scope memories.

        buckets : typing.Dict[str, str]
            Namespace-owned bucket names mapped to descriptions that guide memory classification. Existing names are updated; new names are added.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ProfileBuckets
            Updated effective namespace profile bucket definitions

        Examples
        --------
        import asyncio

        from supermemory import AsyncSupermemory

        client = AsyncSupermemory(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.profiles.set_buckets(
                namespace="user_alex",
                buckets={"interests": "Topics the subject actively follows"},
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.set_buckets(namespace, buckets=buckets, request_options=request_options)
        return _response.data

    async def delete_buckets(
        self,
        namespace: str,
        *,
        buckets: typing.Sequence[str],
        request_options: typing.Optional[RequestOptions] = None,
        extra_headers: typing.Optional[typing.Mapping[str, str]] = None,
        extra_query: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        extra_body: typing.Optional[typing.Mapping[str, typing.Any]] = None,
        timeout: typing.Union[float, httpx.Timeout, None, NotGiven] = NOT_GIVEN,
    ) -> ProfileBuckets:
        """
        Remove profile categories created specifically for this namespace. Unknown names are safely ignored, while organization-wide buckets remain protected.

        Parameters
        ----------
        namespace : str
            The isolated namespace to search. This can be an ID for your user, a project ID, or any other identifier you wish to use to scope memories.

        buckets : typing.Sequence[str]
            Namespace-owned bucket names to delete. Organization-level buckets are protected and cannot be removed here.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ProfileBuckets
            Updated effective namespace profile bucket definitions

        Examples
        --------
        import asyncio

        from supermemory import AsyncSupermemory

        client = AsyncSupermemory(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.profiles.delete_buckets(
                namespace="user_alex",
                buckets=["interests"],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_buckets(namespace, buckets=buckets, request_options=request_options)
        return _response.data
