# This file was auto-generated by Fern from our API Definition.

import typing

from .error_response import ErrorResponse
from .validation_error_response import ValidationErrorResponse

BadRequestErrorBody = typing.Union[ErrorResponse, ValidationErrorResponse]
