# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel
from .chunk_system import ChunkSystem


class ChunkListItem(UncheckedBaseModel):
    id: str = pydantic.Field()
    """
    Stable chunk identifier
    """

    position: int = pydantic.Field()
    """
    Zero-based order within the document
    """

    content: str = pydantic.Field()
    """
    Chunk text used for retrieval
    """

    type: str = pydantic.Field()
    """
    Chunk content type
    """

    metadata: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    Chunk metadata, when available
    """

    system: ChunkSystem = pydantic.Field()
    """
    Lifecycle timestamps maintained by Supermemory
    """

    document_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="documentId"),
        pydantic.Field(alias="documentId", description="ID of the chunk's parent document"),
    ]
    """
    ID of the chunk's parent document
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
