# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel, UnionMetadata
from .google_drive_config import GoogleDriveConfig
from .granola_config import GranolaConfig
from .s3config import S3Config
from .web_crawler_config import WebCrawlerConfig


class ConnectorSetup_Notion(UncheckedBaseModel):
    provider: typing.Literal["notion"] = "notion"
    redirect_url: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="redirectUrl"), pydantic.Field(alias="redirectUrl")
    ] = None
    document_limit: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="documentLimit"), pydantic.Field(alias="documentLimit")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class ConnectorSetup_Gmail(UncheckedBaseModel):
    provider: typing.Literal["gmail"] = "gmail"
    redirect_url: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="redirectUrl"), pydantic.Field(alias="redirectUrl")
    ] = None
    document_limit: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="documentLimit"), pydantic.Field(alias="documentLimit")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class ConnectorSetup_Onedrive(UncheckedBaseModel):
    provider: typing.Literal["onedrive"] = "onedrive"
    redirect_url: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="redirectUrl"), pydantic.Field(alias="redirectUrl")
    ] = None
    document_limit: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="documentLimit"), pydantic.Field(alias="documentLimit")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class ConnectorSetup_Github(UncheckedBaseModel):
    provider: typing.Literal["github"] = "github"
    redirect_url: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="redirectUrl"), pydantic.Field(alias="redirectUrl")
    ] = None
    document_limit: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="documentLimit"), pydantic.Field(alias="documentLimit")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class ConnectorSetup_GoogleDrive(UncheckedBaseModel):
    provider: typing.Literal["google-drive"] = "google-drive"
    redirect_url: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="redirectUrl"), pydantic.Field(alias="redirectUrl")
    ] = None
    document_limit: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="documentLimit"), pydantic.Field(alias="documentLimit")
    ] = None
    config: typing.Optional[GoogleDriveConfig] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class ConnectorSetup_S3(UncheckedBaseModel):
    provider: typing.Literal["s3"] = "s3"
    config: S3Config
    document_limit: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="documentLimit"), pydantic.Field(alias="documentLimit")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class ConnectorSetup_WebCrawler(UncheckedBaseModel):
    provider: typing.Literal["web-crawler"] = "web-crawler"
    config: WebCrawlerConfig
    document_limit: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="documentLimit"), pydantic.Field(alias="documentLimit")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class ConnectorSetup_Granola(UncheckedBaseModel):
    provider: typing.Literal["granola"] = "granola"
    config: GranolaConfig
    document_limit: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="documentLimit"), pydantic.Field(alias="documentLimit")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


ConnectorSetup = typing_extensions.Annotated[
    typing.Union[
        ConnectorSetup_Notion,
        ConnectorSetup_Gmail,
        ConnectorSetup_Onedrive,
        ConnectorSetup_Github,
        ConnectorSetup_GoogleDrive,
        ConnectorSetup_S3,
        ConnectorSetup_WebCrawler,
        ConnectorSetup_Granola,
    ],
    UnionMetadata(discriminant="provider"),
]
