# This file was auto-generated by Fern from our API Definition.

import typing

ConnectorProvider = typing.Union[
    typing.Literal["notion", "google-drive", "onedrive", "gmail", "github", "web-crawler", "s3", "granola"], typing.Any
]
