# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel


class ConnectorSetupNotion(UncheckedBaseModel):
    redirect_url: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="redirectUrl"),
        pydantic.Field(alias="redirectUrl", description="Where the user returns after authorizing with the provider"),
    ] = None
    """
    Where the user returns after authorizing with the provider
    """

    document_limit: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="documentLimit"),
        pydantic.Field(alias="documentLimit", description="Maximum documents this connector imports"),
    ] = None
    """
    Maximum documents this connector imports
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
