# This file was auto-generated by Fern from our API Definition.

import typing

ConnectorErrorCode = typing.Union[
    typing.Literal["auth_expired", "rate_limited", "plan_required", "provider_unavailable", "internal"], typing.Any
]
