# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel


class ConnectorSyncFailure(UncheckedBaseModel):
    document_id: typing_extensions.Annotated[str, FieldMetadata(alias="documentId"), pydantic.Field(alias="documentId")]
    title: typing.Optional[str] = None
    error_code: typing_extensions.Annotated[str, FieldMetadata(alias="errorCode"), pydantic.Field(alias="errorCode")]
    error_message: typing_extensions.Annotated[
        str, FieldMetadata(alias="errorMessage"), pydantic.Field(alias="errorMessage")
    ]
    failed_at: typing_extensions.Annotated[str, FieldMetadata(alias="failedAt"), pydantic.Field(alias="failedAt")]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
