# This file was auto-generated by Fern from our API Definition.

import typing

DocumentSystemStatus = typing.Union[
    typing.Literal["unknown", "queued", "extracting", "chunking", "embedding", "indexing", "done", "failed"], typing.Any
]
