# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, update_forward_refs
from ..core.unchecked_base_model import UncheckedBaseModel


class FilterOr(UncheckedBaseModel):
    operator: typing.Literal["or"] = pydantic.Field(default="or")
    """
    Require at least one nested filter expression to match
    """

    operands: typing.List["FilterExpression"] = pydantic.Field()
    """
    Filter expressions combined with logical OR
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


from .filter_and import FilterAnd  # noqa: E402, I001
from .filter_expression import FilterExpression  # noqa: E402, I001

update_forward_refs(FilterOr, FilterAnd=FilterAnd, FilterExpression=FilterExpression)
