# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel
from .filter_string_contains_operator import FilterStringContainsOperator


class FilterStringContains(UncheckedBaseModel):
    field: str = pydantic.Field()
    """
    Metadata key to evaluate, matched literally. A period is part of the key name, not a path into nested metadata.
    """

    operator: FilterStringContainsOperator = pydantic.Field()
    """
    Require or exclude a substring match
    """

    value: str = pydantic.Field()
    """
    Substring to look for
    """

    case_sensitive: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="caseSensitive"),
        pydantic.Field(alias="caseSensitive", description="Whether substring matching preserves letter case"),
    ] = None
    """
    Whether substring matching preserves letter case
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
