# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .filter_array_contains_operator import FilterArrayContainsOperator


class FilterArrayContains(UncheckedBaseModel):
    field: str = pydantic.Field()
    """
    Metadata key to evaluate, matched literally. A period is part of the key name, not a path into nested metadata.
    """

    operator: FilterArrayContainsOperator = pydantic.Field()
    """
    Require or exclude an exact array member
    """

    value: str = pydantic.Field()
    """
    Array member to look for
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
