# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .chunk_list_item import ChunkListItem
from .document_list_item import DocumentListItem
from .memory import Memory
from .pagination import Pagination


class ListResponse(UncheckedBaseModel):
    """
    A namespace-scoped page of one resource type
    """

    documents: typing.List[DocumentListItem] = pydantic.Field()
    """
    Documents on this page; empty when a different resource type is requested
    """

    chunks: typing.List[ChunkListItem] = pydantic.Field()
    """
    Chunks on this page; empty when a different resource type is requested
    """

    memories: typing.List[Memory] = pydantic.Field()
    """
    Memories on this page; empty when a different resource type is requested
    """

    pagination: Pagination = pydantic.Field()
    """
    Page metadata for the selected resource collection
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
