# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel
from .memory_system import MemorySystem


class Memory(UncheckedBaseModel):
    """
    A memory formed from documents in this namespace
    """

    id: str = pydantic.Field()
    """
    Stable memory identifier
    """

    memory: str = pydantic.Field()
    """
    Learned fact or context extracted from the document
    """

    metadata: typing.Dict[str, typing.Any] = pydantic.Field()
    """
    Memory metadata, including temporal context; empty object when none
    """

    is_static: typing_extensions.Annotated[
        bool,
        FieldMetadata(alias="isStatic"),
        pydantic.Field(alias="isStatic", description="Whether the memory belongs to the stable profile section"),
    ]
    """
    Whether the memory belongs to the stable profile section
    """

    is_inference: typing_extensions.Annotated[
        bool,
        FieldMetadata(alias="isInference"),
        pydantic.Field(
            alias="isInference", description="Whether the memory was inferred rather than explicitly stated"
        ),
    ]
    """
    Whether the memory was inferred rather than explicitly stated
    """

    is_latest: typing_extensions.Annotated[
        bool,
        FieldMetadata(alias="isLatest"),
        pydantic.Field(alias="isLatest", description="Whether this is the newest version in its memory chain"),
    ]
    """
    Whether this is the newest version in its memory chain
    """

    is_forgotten: typing_extensions.Annotated[
        bool,
        FieldMetadata(alias="isForgotten"),
        pydantic.Field(alias="isForgotten", description="Whether this memory has been excluded from normal recall"),
    ]
    """
    Whether this memory has been excluded from normal recall
    """

    version: int = pydantic.Field()
    """
    Version number within the memory chain
    """

    system: MemorySystem = pydantic.Field()
    """
    Lifecycle timestamps maintained by Supermemory
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
