# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .memory_included_related_parents_item_document import MemoryIncludedRelatedParentsItemDocument
from .memory_included_related_parents_item_system import MemoryIncludedRelatedParentsItemSystem
from .memory_relation import MemoryRelation


class MemoryIncludedRelatedParentsItem(UncheckedBaseModel):
    id: str = pydantic.Field()
    """
    Related memory ID
    """

    relation: MemoryRelation = pydantic.Field()
    """
    How this memory is connected to the matched memory
    """

    version: typing.Optional[float] = pydantic.Field(default=None)
    """
    Version number within the related memory's history
    """

    memory: str = pydantic.Field()
    """
    Related learned fact or context
    """

    metadata: typing.Dict[str, typing.Any] = pydantic.Field()
    """
    Public metadata associated with the related memory
    """

    system: MemoryIncludedRelatedParentsItemSystem = pydantic.Field()
    """
    Lifecycle details for the related memory
    """

    document: typing.Optional[MemoryIncludedRelatedParentsItemDocument] = pydantic.Field(default=None)
    """
    Source document; present when include has both related and documents
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
