# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .related_memory import RelatedMemory


class RelatedMemories(UncheckedBaseModel):
    """
    Memory relationships included when requested
    """

    parents: typing.List[RelatedMemory] = pydantic.Field()
    """
    Earlier memories this result updates or derives from
    """

    children: typing.List[RelatedMemory] = pydantic.Field()
    """
    Newer memories that update or extend this result
    """

    siblings: typing.List[RelatedMemory] = pydantic.Field()
    """
    Other memories derived from related context
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
