# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.serialization import FieldMetadata
from ..core.unchecked_base_model import UncheckedBaseModel
from .search_result import SearchResult


class SearchResponse(UncheckedBaseModel):
    results: typing.List[SearchResult] = pydantic.Field()
    """
    Ranked memories and source chunks matching the query
    """

    search_time: typing_extensions.Annotated[
        float,
        FieldMetadata(alias="searchTime"),
        pydantic.Field(alias="searchTime", description="Server-side search duration in milliseconds"),
    ]
    """
    Server-side search duration in milliseconds
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
