# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class SearchRequestAttach(UncheckedBaseModel):
    """
    Optional context to include alongside each matching result
    """

    documents: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Attach the source document for each result when one is available
    """

    related: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Attach parent, child, and sibling memories that explain how each memory evolved
    """

    forgotten: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Allow forgotten memories to participate in recall
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
