# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .validation_error_response_error_item import ValidationErrorResponseErrorItem


class ValidationErrorResponse(UncheckedBaseModel):
    """
    Body returned when request input fails schema validation
    """

    success: typing.Literal[False] = False
    error: typing.List[ValidationErrorResponseErrorItem] = pydantic.Field()
    """
    Validation issues
    """

    data: typing.Optional[typing.Any] = pydantic.Field(default=None)
    """
    The input that failed validation
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
