# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .validation_error_response_error_item_path_item import ValidationErrorResponseErrorItemPathItem


class ValidationErrorResponseErrorItem(UncheckedBaseModel):
    message: str
    path: typing.Optional[typing.List[ValidationErrorResponseErrorItemPathItem]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
