# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.serialization import FieldMetadata
from ...core.unchecked_base_model import UncheckedBaseModel
from .list_namespaces_response_namespaces_item_system import ListNamespacesResponseNamespacesItemSystem


class ListNamespacesResponseNamespacesItem(UncheckedBaseModel):
    id: str = pydantic.Field()
    """
    Internal identifier for the namespace
    """

    namespace: str = pydantic.Field()
    """
    Namespace identifier used in API paths
    """

    document_count: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="documentCount"),
        pydantic.Field(alias="documentCount", description="Number of active source documents in the namespace"),
    ]
    """
    Number of active source documents in the namespace
    """

    memory_count: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="memoryCount"),
        pydantic.Field(alias="memoryCount", description="Number of current, recallable memories in the namespace"),
    ]
    """
    Number of current, recallable memories in the namespace
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Human-readable purpose or scope of the namespace
    """

    system: ListNamespacesResponseNamespacesItemSystem = pydantic.Field()
    """
    Namespace lifecycle timestamps
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
